//- def_Window_Key.h
//--------------------------------------------------------
//Info 
// - Administrator: Á¶ÁØ¿µ.
//--------------------------------------------------------

#pragma once

#define UI_INT(Attr,Option)		   *(int*)(##Attr->Get(Option))
#define UI_STRING(Attr,Option)	   (char*)(##Attr->Get(Option))
#define UI_FLOAT(Attr,Option)	   *(float*)(##Attr->Get(Option))


//- SPWindow.
//{
#define GET_SPWINDOW_PARENT                         1100
#define GET_SPWINDOW_CLASSID                        1101
#define GET_SPWINDOW_INSTANCEID                     1102
#define GET_SPWINDOW_WINDOWTYPE                     1103
#define GET_SPWINDOW_MOVABLE                        1104
#define GET_SPWINDOW_IMAGE_FILENAME                 1105
#define GET_SPWINDOW_IMAGE_X                        1106
#define GET_SPWINDOW_IMAGE_Y                        1107
#define GET_SPWINDOW_X								1108
#define GET_SPWINDOW_Y								1109
#define GET_SPWINDOW_CX								1110	
#define GET_SPWINDOW_CY								1111		
#define GET_SPWINDOW_FONTTYPE                       1112
#define GET_SPWINDOW_FONTSIZE                       1113
#define GET_SPWINDOW_FONT_R							1114 
#define GET_SPWINDOW_FONT_G							1115 
#define GET_SPWINDOW_FONT_B							1116 
#define GET_SPWINDOW_FONT_A							1117
#define GET_SPWINDOW_ALIGN							1118
#define GET_SPWINDOW_REALSIZE_X						1119
#define GET_SPWINDOW_REALSIZE_Y						1120
#define GET_SPWINDOW_FONTCOLOR					    1121

#define SET_SPWINDOW_PARENT                         1200
#define SET_SPWINDOW_CLASSID                        1201
#define SET_SPWINDOW_INSTANCEID                     1202
#define SET_SPWINDOW_WINDOWTYPE                     1203
#define SET_SPWINDOW_MOVABLE                        1204
#define SET_SPWINDOW_IMAGE_FILENAME                 1205
#define SET_SPWINDOW_IMAGE_X                        1206
#define SET_SPWINDOW_IMAGE_Y                        1207
#define SET_SPWINDOW_X								1208
#define SET_SPWINDOW_Y								1209
#define SET_SPWINDOW_CX								1210	
#define SET_SPWINDOW_CY								1211		
#define SET_SPWINDOW_FONTTYPE                       1212
#define SET_SPWINDOW_FONTSIZE                       1213
#define SET_SPWINDOW_FONT_R							1214 
#define SET_SPWINDOW_FONT_G							1215 
#define SET_SPWINDOW_FONT_B							1216 
#define SET_SPWINDOW_FONT_A							1217
#define SET_SPWINDOW_ALIGN							1218
#define SET_SPWINDOW_REALSIZE_X						1219
#define SET_SPWINDOW_REALSIZE_Y						1220
#define SET_SPWINDOW_FONTCOLOR					    1221

// No req var.
#define GET_SPWINDOW_DEPENDENT_X                    1300
#define GET_SPWINDOW_DEPENDENT_Y                    1301
#define GET_SPWINDOW_DEPENDENT_CX                   1302
#define GET_SPWINDOW_DEPENDENT_CY                   1303
#define GET_SPWINDOW_SRCRECT                        1304
//} - SPWindow end.



//- SPWindowButton.
//{
#define GET_SPWINDOW_BUTTON_FILENAME_DISABLE        2101
#define GET_SPWINDOW_BUTTON_DISABLE_X				2102
#define GET_SPWINDOW_BUTTON_DISABLE_Y				2103
#define GET_SPWINDOW_BUTTON_FILENAME_HIT			2104
#define GET_SPWINDOW_BUTTON_HIT_X					2105
#define GET_SPWINDOW_BUTTON_HIT_Y					2106
#define GET_SPWINDOW_BUTTON_FILENAME_PUSH			2107
#define GET_SPWINDOW_BUTTON_PUSH_X					2108
#define GET_SPWINDOW_BUTTON_PUSH_Y					2109
#define GET_SPWINDOW_BUTTON_FILENAME_CHECK          2110
#define GET_SPWINDOW_BUTTON_CHECK_X                 2111
#define GET_SPWINDOW_BUTTON_CHECK_Y                 2112

#define SET_SPWINDOW_BUTTON_FILENAME_DISABLE        2201
#define SET_SPWINDOW_BUTTON_DISABLE_X				2202
#define SET_SPWINDOW_BUTTON_DISABLE_Y				2203
#define SET_SPWINDOW_BUTTON_FILENAME_HIT			2204
#define SET_SPWINDOW_BUTTON_HIT_X					2205
#define SET_SPWINDOW_BUTTON_HIT_Y					2206
#define SET_SPWINDOW_BUTTON_FILENAME_PUSH			2207
#define SET_SPWINDOW_BUTTON_PUSH_X					2208
#define SET_SPWINDOW_BUTTON_PUSH_Y					2209
#define SET_SPWINDOW_BUTTON_FILENAME_CHECK          2210
#define SET_SPWINDOW_BUTTON_CHECK_X                 2211
#define SET_SPWINDOW_BUTTON_CHECK_Y                 2212
//} - SPWindowButton end.



//- SPWindowStatic
//{ 
#define GET_SPWINDOW_STATIC_FILENAME                3101
#define GET_SPWINDOW_STATIC_X						3102
#define GET_SPWINDOW_STATIC_Y						3103
#define GET_SPWINDOW_STATIC_NORMALBODY              3104
#define GET_SPWINDOW_STATIC_TEXT					3109

#define SET_SPWINDOW_STATIC_FILENAME                3201
#define SET_SPWINDOW_STATIC_X						3202
#define SET_SPWINDOW_STATIC_Y						3203
#define SET_SPWINDOW_STATIC_NORMALBODY_FILENAME     3204
#define SET_SPWINDOW_STATIC_NORMALBODY_X		    3205
#define SET_SPWINDOW_STATIC_NORMALBODY_Y		    3206
#define SET_SPWINDOW_STATIC_NORMALBODY_CX		    3207
#define SET_SPWINDOW_STATIC_NORMALBODY_CY		    3208
#define SET_SPWINDOW_STATIC_TEXT					3209
//}  - SPWindowStatic end.



//- SPWindowEdit
//{
#define GET_SPWINDOW_EDIT_R							4101 
#define GET_SPWINDOW_EDIT_G							4102 
#define GET_SPWINDOW_EDIT_B							4103 
#define GET_SPWINDOW_EDIT_A							4104

#define SET_SPWINDOW_EDIT_R							4201 
#define SET_SPWINDOW_EDIT_G							4202 
#define SET_SPWINDOW_EDIT_B							4203 
#define SET_SPWINDOW_EDIT_A							4204 
//} - SPWindowEdit end.


//- SPWindowGauge
//{
#define GET_SPWINDOW_GAUGE_SET						5101
#define GET_SPWINDOW_GAUGE_EDGE_SET					5102
#define GET_SPWINDOW_GAUGE_DECO_SET					5103
#define GET_SPWINDOW_GAUGE_FRAMEHEAD_SET			5104
#define GET_SPWINDOW_GAUGE_FRAMEBODY_SET			5105
#define GET_SPWINDOW_GAUGE_FRAMETAIL_SET			5106
#define GET_SPWINDOW_GAUGE_FLICKER_SET				5107
#define GET_SPWINDOW_GAUGE_FLICKER_EDGE_SET			5108
#define GET_SPWINDOW_GAUGE_FLICKER_DECO_SET			5109

#define SET_SPWINDOW_GAUGE_FILENAME					5201
#define SET_SPWINDOW_GAUGE_X 						5202
#define SET_SPWINDOW_GAUGE_Y 						5203
#define SET_SPWINDOW_GAUGE_CX 						5204
#define SET_SPWINDOW_GAUGE_CY 						5205
#define SET_SPWINDOW_GAUGE_EDGE_FILENAME	  	    5206
#define SET_SPWINDOW_GAUGE_EDGE_X 					5207
#define SET_SPWINDOW_GAUGE_EDGE_Y 					5208
#define SET_SPWINDOW_GAUGE_EDGE_CX 					5209
#define SET_SPWINDOW_GAUGE_EDGE_CY 					5210
#define SET_SPWINDOW_GAUGE_DECO_FILENAME	  	    5211
#define SET_SPWINDOW_GAUGE_DECO_X 					5212
#define SET_SPWINDOW_GAUGE_DECO_Y 					5213
#define SET_SPWINDOW_GAUGE_DECO_CX 					5214
#define SET_SPWINDOW_GAUGE_DECO_CY 					5215
#define SET_SPWINDOW_GAUGE_FRAMEHEAD_FILENAME	  	5216
#define SET_SPWINDOW_GAUGE_FRAMEHEAD_X 				5217
#define SET_SPWINDOW_GAUGE_FRAMEHEAD_Y 				5218
#define SET_SPWINDOW_GAUGE_FRAMEHEAD_CX 			5219
#define SET_SPWINDOW_GAUGE_FRAMEHEAD_CY 			5220
#define SET_SPWINDOW_GAUGE_FRAMEBODY_FILENAME	  	5221
#define SET_SPWINDOW_GAUGE_FRAMEBODY_X 				5222
#define SET_SPWINDOW_GAUGE_FRAMEBODY_Y 				5223
#define SET_SPWINDOW_GAUGE_FRAMEBODY_CX 			5224
#define SET_SPWINDOW_GAUGE_FRAMEBODY_CY 			5225
#define SET_SPWINDOW_GAUGE_FRAMETAIL_FILENAME	  	5226
#define SET_SPWINDOW_GAUGE_FRAMETAIL_X 				5227
#define SET_SPWINDOW_GAUGE_FRAMETAIL_Y 				5228
#define SET_SPWINDOW_GAUGE_FRAMETAIL_CX 			5229
#define SET_SPWINDOW_GAUGE_FRAMETAIL_CY 			5230
#define SET_SPWINDOW_GAUGE_FLICKER_FILENAME	  	    5231
#define SET_SPWINDOW_GAUGE_FLICKER_X 				5232
#define SET_SPWINDOW_GAUGE_FLICKER_Y 				5233
#define SET_SPWINDOW_GAUGE_FLICKER_CX 				5234
#define SET_SPWINDOW_GAUGE_FLICKER_CY 				5235
#define SET_SPWINDOW_GAUGE_FLICKER_EDGE_FILENAME	5236
#define SET_SPWINDOW_GAUGE_FLICKER_EDGE_X 			5237
#define SET_SPWINDOW_GAUGE_FLICKER_EDGE_Y 			5238
#define SET_SPWINDOW_GAUGE_FLICKER_EDGE_CX 			5239
#define SET_SPWINDOW_GAUGE_FLICKER_EDGE_CY 			5240
#define SET_SPWINDOW_GAUGE_FLICKER_DECO_FILENAME	5241
#define SET_SPWINDOW_GAUGE_FLICKER_DECO_X 			5242
#define SET_SPWINDOW_GAUGE_FLICKER_DECO_Y 			5243
#define SET_SPWINDOW_GAUGE_FLICKER_DECO_CX 			5244
#define SET_SPWINDOW_GAUGE_FLICKER_DECO_CY 			5245
//} - SPWindowGuage end.


//- SPWindowComboBox
//{
#define GET_SPWINDOW_CB_TEXPOS_DROPDOWN_ENABLE		6101		
#define GET_SPWINDOW_CB_TEXPOS_DROPDOWN_HIT			6102			
#define GET_SPWINDOW_CB_TEXPOS_DROPDOWN_PUSH		6103			
#define GET_SPWINDOW_CB_TEXPOS_SCROLLUP_ENABLE		6104		
#define GET_SPWINDOW_CB_TEXPOS_SCROLLUP_HIT			6105			
#define GET_SPWINDOW_CB_TEXPOS_SCROLLUP_PUSH		6106			
#define GET_SPWINDOW_CB_TEXPOS_SCROLLUP_DISABLE		6107		
#define GET_SPWINDOW_CB_TEXPOS_SCROLLDOWN_ENABLE	6108		
#define GET_SPWINDOW_CB_TEXPOS_SCROLLDOWN_HIT		6109			
#define GET_SPWINDOW_CB_TEXPOS_SCROLLDOWN_PUSH		6110		
#define GET_SPWINDOW_CB_TEXPOS_SCROLLDOWN_DISABLE	6111		
#define GET_SPWINDOW_CB_TEXPOS_SLIDER_ENABLE		6112			
#define GET_SPWINDOW_CB_TEXPOS_SLIDER_HIT			6113				
#define GET_SPWINDOW_CB_TEXPOS_SLIDER_PUSH			6114			
#define GET_SPWINDOW_CB_TEXPOS_SLIDER_DISABLE		6115			
#define GET_SPWINDOW_CB_TEXPOS_SLIDERBG_ENABLE		6116		
#define GET_SPWINDOW_CB_TEXPOS_SLIDERBG_HIT			6117			
#define GET_SPWINDOW_CB_TEXPOS_SLIDERBG_PUSH		6118			
#define GET_SPWINDOW_CB_TEXPOS_SLIDERBG_DISABLE		6119		
#define GET_SPWINDOW_CB_TEXPOS_EDITBOX_ENABLE		6120			
#define GET_SPWINDOW_CB_TEXPOS_EDITBOX_HIT			6121			
#define GET_SPWINDOW_CB_TEXPOS_EDITBOX_PUSH			6122			
#define GET_SPWINDOW_CB_TEXPOS_LISTBOX_ENABLE		6123			

#define SET_SPWINDOW_CB_OFFSET_DROPDOWN_X			6201
#define SET_SPWINDOW_CB_OFFSET_DROPDOWN_Y			6202
#define SET_SPWINDOW_CB_SIZE_DROPDOWN_X				6203
#define SET_SPWINDOW_CB_SIZE_DROPDOWN_Y				6204
#define SET_SPWINDOW_CB_POS_DROPDOWN_ENABLE_X       6205
#define SET_SPWINDOW_CB_POS_DROPDOWN_ENABLE_Y		6206
#define SET_SPWINDOW_CB_POS_DROPDOWN_HIT_X			6207
#define SET_SPWINDOW_CB_POS_DROPDOWN_HIT_Y			6208
#define SET_SPWINDOW_CB_POS_DROPDOWN_PUSH_X			6209
#define SET_SPWINDOW_CB_POS_DROPDOWN_PUSH_Y			6210
#define SET_SPWINDOW_CB_OFFSET_EDITBOX_X			6211
#define SET_SPWINDOW_CB_OFFSET_EDITBOX_Y			6212
#define SET_SPWINDOW_CB_POS_EDITBOX_ENABLE_X		6213
#define SET_SPWINDOW_CB_POS_EDITBOX_ENABLE_Y		6214
#define SET_SPWINDOW_CB_POS_EDITBOX_ENABLE_CX		6215
#define SET_SPWINDOW_CB_POS_EDITBOX_ENABLE_CY		6216
#define SET_SPWINDOW_CB_POS_EDITBOX_HIT_X			6217
#define SET_SPWINDOW_CB_POS_EDITBOX_HIT_Y			6218
#define SET_SPWINDOW_CB_POS_EDITBOX_HIT_CX			6219
#define SET_SPWINDOW_CB_POS_EDITBOX_HIT_CY			6220
#define SET_SPWINDOW_CB_POS_EDITBOX_PUSH_X			6221
#define SET_SPWINDOW_CB_POS_EDITBOX_PUSH_Y			6222
#define SET_SPWINDOW_CB_POS_EDITBOX_PUSH_CX			6223
#define SET_SPWINDOW_CB_POS_EDITBOX_PUSH_CY			6224
#define SET_SPWINDOW_CB_POS_SCROLLUP_ENABLE_X		6225
#define SET_SPWINDOW_CB_POS_SCROLLUP_ENABLE_Y		6226
#define SET_SPWINDOW_CB_POS_SCROLLUP_HIT_X			6227
#define SET_SPWINDOW_CB_POS_SCROLLUP_HIT_Y			6228
#define SET_SPWINDOW_CB_POS_SCROLLUP_PUSH_X			6229
#define SET_SPWINDOW_CB_POS_SCROLLUP_PUSH_Y			6230
#define SET_SPWINDOW_CB_POS_SCROLLUP_DISABLE_X		6231
#define SET_SPWINDOW_CB_POS_SCROLLUP_DISABLE_Y		6232
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_ENABLE_X		6233
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_ENABLE_Y		6234
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_HIT_X		6235
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_HIT_Y		6236
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_PUSH_X		6237
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_PUSH_Y		6238
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_DISABLE_X	6239
#define SET_SPWINDOW_CB_POS_SCROLLDOWN_DISABLE_Y	6240
#define SET_SPWINDOW_CB_SIZE_SCROLLUP_X				6241
#define SET_SPWINDOW_CB_SIZE_SCROLLUP_Y				6242
#define SET_SPWINDOW_CB_SIZE_SCROLDOWN_X			6243
#define SET_SPWINDOW_CB_SIZE_SCROLDOWN_Y			6244
#define SET_SPWINDOW_CB_POS_LIST_X					6245
#define SET_SPWINDOW_CB_POS_LIST_Y					6246
#define SET_SPWINDOW_CB_POS_LIST_CX					6247
#define SET_SPWINDOW_CB_POS_LIST_CY					6248
//} - SPWindowComboBox end.




