#ifndef __SPWINDOW_CASHSHOP_H__
#define __SPWINDOW_CASHSHOP_H__

//------------------------------------------------------------------------------------

//#define __CASHSHOP_POINT_SHOP__				1

//------------------------------------------------------------------------------------
class SPTerrainManager;	


#define WIID_CASHSHOP_INFO					(WIID_CASHSHOP + 1)
#define WIID_CASHSHOP_INFO_CASH_SKIN		(WIID_CASHSHOP + 2)
#define WIID_CASHSHOP_INFO_OZ_ICON			(WIID_CASHSHOP + 3)
#define WIID_CASHSHOP_INFO_OZ_TEXT			(WIID_CASHSHOP + 4)
#define WIID_CASHSHOP_INFO_OZ				(WIID_CASHSHOP + 5)
#define WIID_CASHSHOP_INFO_MILEAGE_ICON		(WIID_CASHSHOP + 6)
#define WIID_CASHSHOP_INFO_MILEAGE_TEXT		(WIID_CASHSHOP + 7)
#define WIID_CASHSHOP_INFO_MILEAGE			(WIID_CASHSHOP + 8)
#define WIID_CASHSHOP_INFO_FILLING			(WIID_CASHSHOP + 9)
#define WIID_CASHSHOP_INFO_UPDATE			(WIID_CASHSHOP + 10)
#define WIID_CASHSHOP_INFO_COUPON			(WIID_CASHSHOP + 11)
#define WIID_CASHSHOP_INFO_GB2				(WIID_CASHSHOP + 12)
#define WIID_CASHSHOP_EXIT					(WIID_CASHSHOP + 13)


#define WIID_CASHSHOP_ITEM_INVEN			(WIID_CASHSHOP + 15)
#define WIID_CASHSHOP_ITEM_INVEN_WHITE_BG	(WIID_CASHSHOP + 16)
#define WIID_CASHSHOP_ITEM_INVEN_EQUIP		(WIID_CASHSHOP + 17)
#define WIID_CASHSHOP_ITEM_INVEN_CONSUME	(WIID_CASHSHOP + 18)
#define WIID_CASHSHOP_ITEM_INVEN_ETC		(WIID_CASHSHOP + 19)
#define WIID_CASHSHOP_ITEM_INVEN_EVENT		(WIID_CASHSHOP + 20)
#define WIID_CASHSHOP_ITEM_INVEN_PET		(WIID_CASHSHOP + 21)
#define WIID_CASHSHOP_ITEM_INVEN_HOUSING	(WIID_CASHSHOP + 22)
#define WIID_CASHSHOP_ITEM_INVEN_UP			(WIID_CASHSHOP + 23)
#define WIID_CASHSHOP_ITEM_INVEN_DOWN		(WIID_CASHSHOP + 24)
#define WIID_CASHSHOP_ITEM_INVEN_THUMB		(WIID_CASHSHOP + 25)
#define WIID_CASHSHOP_ITEM_INVEN_SLOT		(WIID_CASHSHOP + 26)
#define WIID_CASHSHOP_ITEM_INVEN_TITLE		(WIID_CASHSHOP + 27)
#define WIID_CASHSHOP_ITEM_INVEN_ADDFRAME	(WIID_CASHSHOP + 28)
#define WIID_CASHSHOP_ITEM_INVEN_ADDEQUIP	(WIID_CASHSHOP + 29)
#define WIID_CASHSHOP_ITEM_INVEN_ADDCONSUME	(WIID_CASHSHOP + 30)
#define WIID_CASHSHOP_ITEM_INVEN_ADDETC		(WIID_CASHSHOP + 31)
#define WIID_CASHSHOP_ITEM_INVEN_ADDEVENT	(WIID_CASHSHOP + 32)
#define WIID_CASHSHOP_ITEM_INVEN_ADDPET		(WIID_CASHSHOP + 33)
#define WIID_CASHSHOP_ITEM_INVEN_ADDWH  	(WIID_CASHSHOP + 34)
#define WIID_CASHSHOP_ITEM_INVEN_SELL		(WIID_CASHSHOP + 35)

#define WIID_CASHSHOP_OZ_INVEN				(WIID_CASHSHOP + 38)
#define WIID_CASHSHOP_OZ_INVEN_BUYINFO		(WIID_CASHSHOP + 39)
#define WIID_CASHSHOP_OZ_INVEN_WEARINFO		(WIID_CASHSHOP + 40)
#define WIID_CASHSHOP_OZ_INVEN_WHITE_BG		(WIID_CASHSHOP + 41)
#define WIID_CASHSHOP_OZ_INVEN_LEFT			(WIID_CASHSHOP + 42)
#define WIID_CASHSHOP_OZ_INVEN_RIGHT		(WIID_CASHSHOP + 43)
#define WIID_CASHSHOP_OZ_INVEN_THUMB		(WIID_CASHSHOP + 44)
#define WIID_CASHSHOP_OZ_INVEN_LINE_BG    	(WIID_CASHSHOP + 45)
#define WIID_CASHSHOP_OZ_INVEN_MID_BG    	(WIID_CASHSHOP + 46)
#define WIID_CASHSHOP_OZ_INVEN_SLOT			(WIID_CASHSHOP + 47)
#define WIID_CASHSHOP_OZ_SELL				(WIID_CASHSHOP + 48)
#define WIID_CASHSHOP_OZ_SELL_HELP			(WIID_CASHSHOP + 49)

#define WIID_CASHSHOP_STORE					(WIID_CASHSHOP + 55)
#define WIID_CASHSHOP_STORE_TOP				(WIID_CASHSHOP + 56)
#define WIID_CASHSHOP_STORE_BUTTOM			(WIID_CASHSHOP + 57)
#define WIID_CASHSHOP_STORE_LEFT			(WIID_CASHSHOP + 58)
#define WIID_CASHSHOP_STORE_RIGHT			(WIID_CASHSHOP + 59)
#define WIID_CASHSHOP_STORE_MID				(WIID_CASHSHOP + 60)
#define WIID_CASHSHOP_STORE_LIST_SKIN		(WIID_CASHSHOP + 61)
#define WIID_CASHSHOP_STORE_EVENT			(WIID_CASHSHOP + 62)
#define WIID_CASHSHOP_STORE_FASSION			(WIID_CASHSHOP + 63)
#define WIID_CASHSHOP_STORE_PET				(WIID_CASHSHOP + 64)
#define WIID_CASHSHOP_STORE_ETC				(WIID_CASHSHOP + 65)
#define WIID_CASHSHOP_STORE_PACKAGE			(WIID_CASHSHOP + 66)
#define WIID_CASHSHOP_STORE_SEARCH			(WIID_CASHSHOP + 67)
#define WIID_CASHSHOP_STORE_HELP			(WIID_CASHSHOP + 68)

#define WIID_CASHSHOP_STORE_POINT			(WIID_CASHSHOP + 70)

#define WIID_CASHSHOP_STORE_EVENT_NEW		(WIID_CASHSHOP + 81)
#define WIID_CASHSHOP_STORE_EVENT_FAVORITE	(WIID_CASHSHOP + 82)
#define WIID_CASHSHOP_STORE_EVENT_EVENT		(WIID_CASHSHOP + 83)
#define WIID_CASHSHOP_STORE_FASSION_DRESS	(WIID_CASHSHOP + 84)
#define WIID_CASHSHOP_STORE_FASSION_HELMET	(WIID_CASHSHOP + 85)
#define WIID_CASHSHOP_STORE_FASSION_SHOES	(WIID_CASHSHOP + 86)
#define WIID_CASHSHOP_STORE_FASSION_GLOVE	(WIID_CASHSHOP + 87)
#define WIID_CASHSHOP_STORE_FASSION_ACCE	(WIID_CASHSHOP + 88)
#define WIID_CASHSHOP_STORE_FASSION_ETC 	(WIID_CASHSHOP + 89)
#define WIID_CASHSHOP_STORE_PET_PET			(WIID_CASHSHOP + 90)
#define WIID_CASHSHOP_STORE_PET_ETC			(WIID_CASHSHOP + 91)
#define WIID_CASHSHOP_STORE_ETC_FUNCTIONAL	(WIID_CASHSHOP + 92)
#define WIID_CASHSHOP_STORE_ETC_BEAUTY		(WIID_CASHSHOP + 93)
#define WIID_CASHSHOP_STORE_ETC_COMMUNITY	(WIID_CASHSHOP + 94)
#define WIID_CASHSHOP_STORE_PACK_FASSION	(WIID_CASHSHOP + 95)
#define WIID_CASHSHOP_STORE_PACK_PET		(WIID_CASHSHOP + 98)
#define WIID_CASHSHOP_STORE_PACK_HOUSING	(WIID_CASHSHOP + 99)
#define WIID_CASHSHOP_STORE_PACK_PVP		(WIID_CASHSHOP + 100)
#define WIID_CASHSHOP_STORE_PACK_ETC		(WIID_CASHSHOP + 101)

#define WIID_CASHSHOP_STORE_POINT_FASSION	(WIID_CASHSHOP + 102)
#define WIID_CASHSHOP_STORE_POINT_PET		(WIID_CASHSHOP + 103)
#define WIID_CASHSHOP_STORE_POINT_FUNCTIONAL	(WIID_CASHSHOP + 104)

#define WIID_CASHSHOP_STORE_LIST_WHITE_BG	(WIID_CASHSHOP + 105)

#define WIID_CASHSHOP_STORE_FAS_DRESS_POP	(WIID_CASHSHOP + 106)
#define WIID_CASHSHOP_STORE_FAS_HELMET_POP	(WIID_CASHSHOP + 107)
#define WIID_CASHSHOP_STORE_FAS_SHOES_POP	(WIID_CASHSHOP + 108)
#define WIID_CASHSHOP_STORE_FAS_GLOVE_POP	(WIID_CASHSHOP + 109)
#define WIID_CASHSHOP_STORE_FAS_ACCE_POP	(WIID_CASHSHOP + 110)
#define WIID_CASHSHOP_STORE_ETC_COMMU_POP	(WIID_CASHSHOP + 111)

#define WIID_CASHSHOP_STORE_SEARCH_STATIC	(WIID_CASHSHOP + 112)
#define WIID_CASHSHOP_STORE_SEARCH_EDIT_BG	(WIID_CASHSHOP + 113)
#define WIID_CASHSHOP_STORE_SEARCH_EDIT		(WIID_CASHSHOP + 114)
#define WIID_CASHSHOP_STORE_SEARCH_SEARCH	(WIID_CASHSHOP + 115)

#define WIID_CASHSHOP_STORE_FAS_DRESS_TOTAL	(WIID_CASHSHOP + 120)
#define WIID_CASHSHOP_STORE_FAS_DRESS_ONE	(WIID_CASHSHOP + 121)
#define WIID_CASHSHOP_STORE_FAS_DRESS_BLO	(WIID_CASHSHOP + 122)
#define WIID_CASHSHOP_STORE_FAS_DRESS_PAN	(WIID_CASHSHOP + 123)
#define WIID_CASHSHOP_STORE_FAS_DRESS_COAT	(WIID_CASHSHOP + 124)
#define WIID_CASHSHOP_STORE_FAS_HELMET_TOTAL (WIID_CASHSHOP + 130)
#define WIID_CASHSHOP_STORE_FAS_HELMET_HELM  (WIID_CASHSHOP + 131)
#define WIID_CASHSHOP_STORE_FAS_HELMET_BAND  (WIID_CASHSHOP + 132)
#define WIID_CASHSHOP_STORE_FAS_HELMET_PIN   (WIID_CASHSHOP + 133)
#define WIID_CASHSHOP_STORE_FAS_SHOES_TOTAL	(WIID_CASHSHOP + 140)
#define WIID_CASHSHOP_STORE_FAS_SHOES_SHOES	(WIID_CASHSHOP + 141)
#define WIID_CASHSHOP_STORE_FAS_SHOES_BAND	(WIID_CASHSHOP + 142)
#define WIID_CASHSHOP_STORE_FAS_GLOVE_TOTAL	(WIID_CASHSHOP + 143)
#define WIID_CASHSHOP_STORE_FAS_GLOVE_GLOVE	(WIID_CASHSHOP + 144)
#define WIID_CASHSHOP_STORE_FAS_GLOVE_BAND	(WIID_CASHSHOP + 145)
#define WIID_CASHSHOP_STORE_FAS_ACCE_TOTAL	(WIID_CASHSHOP + 150)
#define WIID_CASHSHOP_STORE_FAS_ACCE_GLASS	(WIID_CASHSHOP + 151)
#define WIID_CASHSHOP_STORE_FAS_ACCE_EARING	(WIID_CASHSHOP + 152)
#define WIID_CASHSHOP_STORE_FAS_ACCE_MAKEUP	(WIID_CASHSHOP + 153)
#define WIID_CASHSHOP_STORE_FAS_ACCE_STOCK	(WIID_CASHSHOP + 154)
#define WIID_CASHSHOP_STORE_ETC_COMMU_TOTAL	(WIID_CASHSHOP + 160)
#define WIID_CASHSHOP_STORE_ETC_COMMU_EMOTI	(WIID_CASHSHOP + 161)
#define WIID_CASHSHOP_STORE_ETC_COMMU_EXPRE	(WIID_CASHSHOP + 162)
#define WIID_CASHSHOP_STORE_ETC_COMMU_EVENT	(WIID_CASHSHOP + 163)
#define WIID_CASHSHOP_STORE_ETC_COMMU_CHAT	(WIID_CASHSHOP + 164)
#define WIID_CASHSHOP_STORE_PAGE			(WIID_CASHSHOP + 165)	// +20
#define WIID_CASHSHOP_STORE_SORT_GENDER		(WIID_CASHSHOP + 185)	// +10
#define WIID_CASHSHOP_STORE_SORT_PRICE		(WIID_CASHSHOP + 195)	// +10

#define WIID_CASHSHOP_STORE_ITEM			(WIID_CASHSHOP + 210)	// +10
#define WIID_CASHSHOP_STORE_ITEM_SKIN		(WIID_CASHSHOP + 220)	// +10
#define WIID_CASHSHOP_STORE_ITEM_SKIN_M		(WIID_CASHSHOP + 230)	// +10
#define WIID_CASHSHOP_STORE_ITEM_SLOT_IMAGE	(WIID_CASHSHOP + 240)	// +10
#define WIID_CASHSHOP_STORE_ITEM_IMAGE_BG	(WIID_CASHSHOP + 250)	// +10
#define WIID_CASHSHOP_STORE_ITEM_IMAGE		(WIID_CASHSHOP + 260)	// +10
#define WIID_CASHSHOP_STORE_ITEM_NAME_BG	(WIID_CASHSHOP + 270)	// +10
#define WIID_CASHSHOP_STORE_ITEM_NAME		(WIID_CASHSHOP + 280)	// +10
#define WIID_CASHSHOP_STORE_ITEM_GENDER		(WIID_CASHSHOP + 290)	// +10
#define WIID_CASHSHOP_STORE_ITEM_GENDER_W	(WIID_CASHSHOP + 300)	// +10
#define WIID_CASHSHOP_STORE_ITEM_GENDER_M	(WIID_CASHSHOP + 310)	// +10
#define WIID_CASHSHOP_STORE_ITEM_SKIN_W		(WIID_CASHSHOP + 320)	// +10
#define WIID_CASHSHOP_STORE_ITEM_OZ_IMAGE	(WIID_CASHSHOP + 330)	// +10
#define WIID_CASHSHOP_STORE_ITEM_PRICE		(WIID_CASHSHOP + 340)	// +10
#define WIID_CASHSHOP_STORE_ITEM_SALE_PRICE	(WIID_CASHSHOP + 350)	// +10
#define WIID_CASHSHOP_STORE_ITEM_BUY		(WIID_CASHSHOP + 360)	// +10
#define WIID_CASHSHOP_STORE_ITEM_GIFT		(WIID_CASHSHOP + 370)	// +10
#define WIID_CASHSHOP_STORE_ITEM_EXACT		(WIID_CASHSHOP + 380)	// +10
#define WIID_CASHSHOP_STORE_ITEM_PRICE_BACK	(WIID_CASHSHOP + 390)	// +10

#define WIID_CASHSHOP_PREVIEW				(WIID_CASHSHOP + 400)
#define WIID_CASHSHOP_PREVIEW_TITLE			(WIID_CASHSHOP + 401)
#define WIID_CASHSHOP_PREVIEW_WHITE_BG		(WIID_CASHSHOP + 402)
#define WIID_CASHSHOP_PREVIEW_LEFT			(WIID_CASHSHOP + 403)
#define WIID_CASHSHOP_PREVIEW_RIGHT			(WIID_CASHSHOP + 404)
#define WIID_CASHSHOP_PREVIEW_PAGE_TEXT		(WIID_CASHSHOP + 405)
#define WIID_CASHSHOP_PREVIEW_SLOT			(WIID_CASHSHOP + 406)
#define WIID_CASHSHOP_PREVIEW_PRICE_BG		(WIID_CASHSHOP + 407)
#define WIID_CASHSHOP_PREVIEW_OZ_IMAGE		(WIID_CASHSHOP + 408)
#define WIID_CASHSHOP_PREVIEW_PRICE			(WIID_CASHSHOP + 409)
#define WIID_CASHSHOP_PREVIEW_BUY			(WIID_CASHSHOP + 410)
#define WIID_CASHSHOP_PREVIEW_DEL			(WIID_CASHSHOP + 411)
#define WIID_CASHSHOP_PREVIEW_INIT			(WIID_CASHSHOP + 412)
#define WIID_CASHSHOP_CHAR_BG				(WIID_CASHSHOP + 415)
#define WIID_CASHSHOP_CHAR_NORMAL			(WIID_CASHSHOP + 416)
#define WIID_CASHSHOP_CHAR_RUN				(WIID_CASHSHOP + 417)
#define WIID_CASHSHOP_CHAR_LADDER			(WIID_CASHSHOP + 418)
#define WIID_CASHSHOP_CHAR_INIT				(WIID_CASHSHOP + 419)

#define WIID_CASHSHOP_CASHIER				(WIID_CASHSHOP + 420)
#define WIID_CASHSHOP_CASHIER_ITEM_SLOT		(WIID_CASHSHOP + 421)
#define WIID_CASHSHOP_CASHIER_ITEM			(WIID_CASHSHOP + 422)
#define WIID_CASHSHOP_CASHIER_NAME			(WIID_CASHSHOP + 423)
#define WIID_CASHSHOP_CASHIER_PRICE_BG		(WIID_CASHSHOP + 424)
#define WIID_CASHSHOP_CASHIER_OZ_ICON		(WIID_CASHSHOP + 425)
#define WIID_CASHSHOP_CASHIER_PRICE			(WIID_CASHSHOP + 426)
#define WIID_CASHSHOP_CASHIER_USE_OZ_TEXT	(WIID_CASHSHOP + 427)
#define WIID_CASHSHOP_CASHIER_USE_MILE_TEXT	(WIID_CASHSHOP + 428)
#define WIID_CASHSHOP_CASHIER_USE_PRI_TEXT	(WIID_CASHSHOP + 429)
#define WIID_CASHSHOP_CASHIER_MY_OZ_TEXT	(WIID_CASHSHOP + 430)
#define WIID_CASHSHOP_CASHIER_AF_MY_OZ_TEXT	(WIID_CASHSHOP + 431)
#define WIID_CASHSHOP_CASHIER_USE_OZ_ICON	(WIID_CASHSHOP + 432)
#define WIID_CASHSHOP_CASHIER_USE_MILE_ICON	(WIID_CASHSHOP + 433)
#define WIID_CASHSHOP_CASHIER_USE_MILE_BG	(WIID_CASHSHOP + 434)
#define WIID_CASHSHOP_CASHIER_USE_PRI_ICON	(WIID_CASHSHOP + 435)
#define WIID_CASHSHOP_CASHIER_MY_OZ_ICON	(WIID_CASHSHOP + 436)
#define WIID_CASHSHOP_CASHIER_AF_MY_OZ_ICON	(WIID_CASHSHOP + 437)
#define WIID_CASHSHOP_CASHIER_USE_OZ		(WIID_CASHSHOP + 438)
#define WIID_CASHSHOP_CASHIER_USE_MILE		(WIID_CASHSHOP + 439)
#define WIID_CASHSHOP_CASHIER_USE_PRI		(WIID_CASHSHOP + 440)
#define WIID_CASHSHOP_CASHIER_MY_OZ			(WIID_CASHSHOP + 441)
#define WIID_CASHSHOP_CASHIER_AF_MY_OZ		(WIID_CASHSHOP + 442)
#define WIID_CASHSHOP_CASHIER_PLUS			(WIID_CASHSHOP + 443)
#define WIID_CASHSHOP_CASHIER_MINUS			(WIID_CASHSHOP + 444)
#define WIID_CASHSHOP_CASHIER_TYPE			(WIID_CASHSHOP + 445)
#define WIID_CASHSHOP_CASHIER_OK			(WIID_CASHSHOP + 446)
#define WIID_CASHSHOP_CASHIER_CANCEL		(WIID_CASHSHOP + 447)

#define WIID_CASHSHOP_GIFT					(WIID_CASHSHOP + 450)
#define WIID_CASHSHOP_GIFT_ITEM_SLOT		(WIID_CASHSHOP + 451)
#define WIID_CASHSHOP_GIFT_ITEM				(WIID_CASHSHOP + 452)
#define WIID_CASHSHOP_GIFT_NAME				(WIID_CASHSHOP + 453)
#define WIID_CASHSHOP_GIFT_PRICE_BG			(WIID_CASHSHOP + 454)
#define WIID_CASHSHOP_GIFT_OZ_ICON			(WIID_CASHSHOP + 455)
#define WIID_CASHSHOP_GIFT_PRICE			(WIID_CASHSHOP + 456)
#define WIID_CASHSHOP_GIFT_USE_OZ_TEXT		(WIID_CASHSHOP + 457)
#define WIID_CASHSHOP_GIFT_USE_MILE_TEXT	(WIID_CASHSHOP + 458)
#define WIID_CASHSHOP_GIFT_USE_PRI_TEXT		(WIID_CASHSHOP + 459)
#define WIID_CASHSHOP_GIFT_MY_OZ_TEXT		(WIID_CASHSHOP + 460)
#define WIID_CASHSHOP_GIFT_AF_MY_OZ_TEXT	(WIID_CASHSHOP + 461)
#define WIID_CASHSHOP_GIFT_USE_OZ_ICON		(WIID_CASHSHOP + 462)
#define WIID_CASHSHOP_GIFT_USE_MILE_ICON	(WIID_CASHSHOP + 463)
#define WIID_CASHSHOP_GIFT_USE_MILE_BG		(WIID_CASHSHOP + 464)
#define WIID_CASHSHOP_GIFT_USE_PRICE_ICON	(WIID_CASHSHOP + 465)
#define WIID_CASHSHOP_GIFT_MY_OZ_ICON		(WIID_CASHSHOP + 466)
#define WIID_CASHSHOP_GIFT_AF_MY_OZ_ICON	(WIID_CASHSHOP + 467)
#define WIID_CASHSHOP_GIFT_USE_OZ			(WIID_CASHSHOP + 468)
#define WIID_CASHSHOP_GIFT_USE_MILE			(WIID_CASHSHOP + 469)
#define WIID_CASHSHOP_GIFT_USE_PRI			(WIID_CASHSHOP + 470)
#define WIID_CASHSHOP_GIFT_MY_OZ			(WIID_CASHSHOP + 471)
#define WIID_CASHSHOP_GIFT_AF_MY_OZ			(WIID_CASHSHOP + 472)
#define WIID_CASHSHOP_GIFT_PLUS				(WIID_CASHSHOP + 473)
#define WIID_CASHSHOP_GIFT_MINUS			(WIID_CASHSHOP + 474)
#define WIID_CASHSHOP_GIFT_TYPE				(WIID_CASHSHOP + 475)
#define WIID_CASHSHOP_GIFT_OK				(WIID_CASHSHOP + 476)
#define WIID_CASHSHOP_GIFT_CANCEL			(WIID_CASHSHOP + 477)
#define WIID_CASHSHOP_GIFT_MESSAGE_GRN_BG	(WIID_CASHSHOP + 478)
#define WIID_CASHSHOP_GIFT_RECEIVE_IMG		(WIID_CASHSHOP + 479)
#define WIID_CASHSHOP_GIFT_MESSAGE_IMG		(WIID_CASHSHOP + 480)
#define WIID_CASHSHOP_GIFT_RECEIVE_BG		(WIID_CASHSHOP + 481)
#define WIID_CASHSHOP_GIFT_MESSAGE_BG		(WIID_CASHSHOP + 482)
#define WIID_CASHSHOP_GIFT_MESSAGE			(WIID_CASHSHOP + 483)
#define WIID_CASHSHOP_GIFT_RECEIVE			(WIID_CASHSHOP + 484)
#define WIID_CASHSHOP_GIFT_FRIEND_BTN		(WIID_CASHSHOP + 485)
#define WIID_CASHSHOP_GIFT_FRIEND			(WIID_CASHSHOP + 486)
#define WIID_CASHSHOP_GIFT_FRIEND_LIST_BG	(WIID_CASHSHOP + 487)
#define WIID_CASHSHOP_GIFT_FRIEND_LIST		(WIID_CASHSHOP + 489)
#define WIID_CASHSHOP_GIFT_SKIN				(WIID_CASHSHOP + 490)

#define WIID_CASHSHOP_COUPON				(WIID_CASHSHOP + 500)
#define WIID_CASHSHOP_COUPON_CODE_IMAGE1	(WIID_CASHSHOP + 501)
#define WIID_CASHSHOP_COUPON_CODE_IMAGE2	(WIID_CASHSHOP + 502)
#define WIID_CASHSHOP_COUPON_LOGO			(WIID_CASHSHOP + 503)
#define WIID_CASHSHOP_COUPON_TEXT			(WIID_CASHSHOP + 504)
#define WIID_CASHSHOP_COUPON_NUMBER_IMG		(WIID_CASHSHOP + 505)	// +4
#define WIID_CASHSHOP_COUPON_NUMBER			(WIID_CASHSHOP + 509)	// +4
#define WIID_CASHSHOP_COUPON_LINE			(WIID_CASHSHOP + 513)	// +3
#define WIID_CASHSHOP_COUPON_OK				(WIID_CASHSHOP + 516)
#define WIID_CASHSHOP_COUPON_CANCEL			(WIID_CASHSHOP + 517)

#define WIID_CASHSHOP_SELL					(WIID_CASHSHOP + 520)
#define WIID_CASHSHOP_SELL_ITEM_SLOT		(WIID_CASHSHOP + 521)
#define WIID_CASHSHOP_SELL_ITEM				(WIID_CASHSHOP + 522)
#define WIID_CASHSHOP_SELL_ITEM_NAME		(WIID_CASHSHOP + 523)
#define WIID_CASHSHOP_SELL_MILEAGE_ICON		(WIID_CASHSHOP + 524)
#define WIID_CASHSHOP_SELL_MILEAGE_TEXT		(WIID_CASHSHOP + 525)
#define WIID_CASHSHOP_SELL_MILEAGE			(WIID_CASHSHOP + 526)
#define WIID_CASHSHOP_SELL_INFO_TEXT		(WIID_CASHSHOP + 527)
#define WIID_CASHSHOP_SELL_OK				(WIID_CASHSHOP + 528)
#define WIID_CASHSHOP_SELL_CANCEL			(WIID_CASHSHOP + 529)
#define WIID_CASHSHOP_SELL_COUNT_ICON		(WIID_CASHSHOP + 530)
#define WIID_CASHSHOP_SELL_COUNT_TEXT		(WIID_CASHSHOP + 531)
#define WIID_CASHSHOP_SELL_COUNT			(WIID_CASHSHOP + 532)

#define WIID_CASHSHOP_ERROR					(WIID_CASHSHOP + 540)
#define WIID_CASHSHOP_ERROR_IMAGE			(WIID_CASHSHOP + 541)
#define WIID_CASHSHOP_ERROR_MESSAGE			(WIID_CASHSHOP + 542)
#define WIID_CASHSHOP_ERROR_OK				(WIID_CASHSHOP + 543)
#define WIID_CASHSHOP_NOTICE				(WIID_CASHSHOP + 550)

#define WIID_CASHSHOP_RESULT				(WIID_CASHSHOP + 560)
#define WIID_CASHSHOP_RESULT_ITEM_SLOT		(WIID_CASHSHOP + 561)
#define WIID_CASHSHOP_RESULT_ITEM			(WIID_CASHSHOP + 562)
#define WIID_CASHSHOP_RESULT_ITEM_NAME		(WIID_CASHSHOP + 563)
#define WIID_CASHSHOP_RESULT_PRICE_BG		(WIID_CASHSHOP + 564)
#define WIID_CASHSHOP_RESULT_OZ_ICON		(WIID_CASHSHOP + 565)
#define WIID_CASHSHOP_RESULT_PRICE			(WIID_CASHSHOP + 566)
#define WIID_CASHSHOP_RESULT_BUY_OZ_TEXT	(WIID_CASHSHOP + 567)
#define WIID_CASHSHOP_RESULT_MY_OZ_TEXT		(WIID_CASHSHOP + 568)
#define WIID_CASHSHOP_RESULT_BUY_OZ_ICON	(WIID_CASHSHOP + 569)
#define WIID_CASHSHOP_RESULT_MY_OZ_ICON		(WIID_CASHSHOP + 570)
#define WIID_CASHSHOP_RESULT_BUY_OZ			(WIID_CASHSHOP + 571)
#define WIID_CASHSHOP_RESULT_MY_OZ			(WIID_CASHSHOP + 572)
#define WIID_CASHSHOP_RESULT_OK				(WIID_CASHSHOP + 573)
#define WIID_CASHSHOP_RESULT_MSG			(WIID_CASHSHOP + 574)

#define WIID_CASHSHOP_BUYWAIT				(WIID_CASHSHOP + 600)
#define WIID_CASHSHOP_BUYWAIT_ITEM			(WIID_CASHSHOP + 601)
#define WIID_CASHSHOP_BUYWAIT_PLAYER		(WIID_CASHSHOP + 602)
#define WIID_CASHSHOP_BUYWAIT_TEXT			(WIID_CASHSHOP + 603)
#define WIID_CASHSHOP_BUYWAIT_ANI			(WIID_CASHSHOP + 604)	// +14

//[xialin 2008/07/10] 玩家预览框
#define WIID_CASHSHOP_PLAYERVIEW            (WIID_CASHSHOP + 630)
#define WIID_CASHSHOP_PLAYERVIEW_TITLE      (WIID_CASHSHOP + 631)
#define WIID_CASHSHOP_PLAYERVIEW_BG         (WIID_CASHSHOP + 632)
#define WIID_CASHSHOP_PLAYERVIEW_MIDBG      (WIID_CASHSHOP + 633)
#define WIID_CASHSHOP_PLAYERVIEW_BACK1      (WIID_CASHSHOP + 634)
#define WIID_CASHSHOP_PLAYERVIEW_BACK2      (WIID_CASHSHOP + 635)
#define WIID_CASHSHOP_PLAYERVIEW_BACK3      (WIID_CASHSHOP + 636)
#define WIID_CASHSHOP_PLAYERVIEW_SAVE       (WIID_CASHSHOP + 637)
#define WIID_CASHSHOP_PLAYERVIEW_BUY        (WIID_CASHSHOP + 638)
#define WIID_CASHSHOP_PLAYERVIEW_EXACT      (WIID_CASHSHOP + 639)
#define WIID_CASHSHOP_PLAYERVIEW_INIT       (WIID_CASHSHOP + 640)
#define WIID_CASHSHOP_PLAYERVIEW_WEARINFO   (WIID_CASHSHOP + 641)

//[xialin 2008/07/10] 索要对话框
#define WIID_CASHSHOP_EXACT                 (WIID_CASHSHOP + 650)
#define WIID_CASHSHOP_EXACT_ITEM_SLOT		(WIID_CASHSHOP + 651)
#define WIID_CASHSHOP_EXACT_ITEM			(WIID_CASHSHOP + 652)
#define WIID_CASHSHOP_EXACT_NAME			(WIID_CASHSHOP + 653)
#define WIID_CASHSHOP_EXACT_PRICE_BG		(WIID_CASHSHOP + 654)
#define WIID_CASHSHOP_EXACT_OZ_ICON			(WIID_CASHSHOP + 655)
#define WIID_CASHSHOP_EXACT_PRICE			(WIID_CASHSHOP + 656)
#define WIID_CASHSHOP_EXACT_OK				(WIID_CASHSHOP + 657)
#define WIID_CASHSHOP_EXACT_CANCEL			(WIID_CASHSHOP + 658)
#define WIID_CASHSHOP_EXACT_MESSAGE_GRN_BG	(WIID_CASHSHOP + 659)
#define WIID_CASHSHOP_EXACT_RECEIVE_IMG		(WIID_CASHSHOP + 660)
#define WIID_CASHSHOP_EXACT_MESSAGE_IMG		(WIID_CASHSHOP + 661)
#define WIID_CASHSHOP_EXACT_RECEIVE_BG		(WIID_CASHSHOP + 662)
#define WIID_CASHSHOP_EXACT_MESSAGE_BG		(WIID_CASHSHOP + 663)
#define WIID_CASHSHOP_EXACT_MESSAGE			(WIID_CASHSHOP + 664)
#define WIID_CASHSHOP_EXACT_RECEIVE			(WIID_CASHSHOP + 665)
#define WIID_CASHSHOP_EXACT_FRIEND_BTN		(WIID_CASHSHOP + 666)
#define WIID_CASHSHOP_EXACT_FRIEND			(WIID_CASHSHOP + 667)
#define WIID_CASHSHOP_EXACT_FRIEND_LIST_BG	(WIID_CASHSHOP + 668)
#define WIID_CASHSHOP_EXACT_FRIEND_LIST		(WIID_CASHSHOP + 670)
#define WIID_CASHSHOP_EXACT_TEXT            (WIID_CASHSHOP + 671)
#define WIID_CASHSHOP_EXACT_SKIN            (WIID_CASHSHOP + 672)

//配套提示框
#define WIID_CASHSHOP_SULT					(WIID_CASHSHOP + 690)
#define WIID_CASHSHOP_SULT_ITEM_BACK		(WIID_CASHSHOP + 691)
#define WIID_CASHSHOP_SULT_ITEM_EXIT		(WIID_CASHSHOP + 692)
#define WIID_CASHSHOP_SULT_ITEM				(WIID_CASHSHOP + 700)   // +6
#define WIID_CASHSHOP_SULT_ITEM_SKIN		(WIID_CASHSHOP + 706)	// +6
#define WIID_CASHSHOP_SULT_ITEM_SLOT_IMAGE	(WIID_CASHSHOP + 712)	// +6
#define WIID_CASHSHOP_SULT_ITEM_IMAGE_BG	(WIID_CASHSHOP + 718)	// +6
#define WIID_CASHSHOP_SULT_ITEM_IMAGE		(WIID_CASHSHOP + 724)	// +6
#define WIID_CASHSHOP_SULT_ITEM_NAME_BG		(WIID_CASHSHOP + 730)	// +6
#define WIID_CASHSHOP_SULT_ITEM_NAME		(WIID_CASHSHOP + 736)	// +6
#define WIID_CASHSHOP_SULT_ITEM_SKIN_W		(WIID_CASHSHOP + 742)	// +6
#define WIID_CASHSHOP_SULT_ITEM_OZ_IMAGE	(WIID_CASHSHOP + 748)	// +6
#define WIID_CASHSHOP_SULT_ITEM_PRICE		(WIID_CASHSHOP + 754)	// +6
#define WIID_CASHSHOP_SULT_ITEM_SALE_PRICE	(WIID_CASHSHOP + 760)	// +6
#define WIID_CASHSHOP_SULT_ITEM_GENDER      (WIID_CASHSHOP + 766)   // +6
#define WIID_CASHSHOP_SULT_ITEM_BUY			(WIID_CASHSHOP + 772)	// +6
#define WIID_CASHSHOP_SULT_ITEM_GIFT		(WIID_CASHSHOP + 778)	// +6
#define WIID_CASHSHOP_SULT_ITEM_EXACT		(WIID_CASHSHOP + 784)	// +6
#define WIID_CASHSHOP_SULT_PRICE_BACK		(WIID_CASHSHOP + 790)	// +6

//热销排行
#define WIID_CASHSHOP_SORT_TITLE			(WIID_CASHSHOP + 800)
#define WIID_CASHSHOP_SORT				    (WIID_CASHSHOP + 801)
#define WIID_CASHSHOP_SORT_ICON			    (WIID_CASHSHOP + 805)   //+5
#define WIID_CASHSHOP_SORT_NAME			    (WIID_CASHSHOP + 810)   //+5
#define WIID_CASHSHOP_SORT_PRICE			(WIID_CASHSHOP + 815)   //+5

//批量购买
#define WIID_CASHSHOP_BUYLIST				(WIID_CASHSHOP + 820)
#define WIID_CASHSHOP_BUYLIST_ITEMBG		(WIID_CASHSHOP + 825)   //+ 3
#define WIID_CASHSHOP_BUYLIST_ITEM_CHECK	(WIID_CASHSHOP + 828)   //+ 3
#define WIID_CASHSHOP_BUYLIST_ITEM_SLOT		(WIID_CASHSHOP + 831)   //+ 3
#define WIID_CASHSHOP_BUYLIST_ITEM			(WIID_CASHSHOP + 834)   //+ 3
#define WIID_CASHSHOP_BUYLIST_NAME			(WIID_CASHSHOP + 837)   //+ 3
#define WIID_CASHSHOP_BUYLIST_PRICE_BG		(WIID_CASHSHOP + 840)	//+ 3
#define WIID_CASHSHOP_BUYLIST_OZ_ICON		(WIID_CASHSHOP + 843)	//+ 3
#define WIID_CASHSHOP_BUYLIST_PRICE			(WIID_CASHSHOP + 846)	//+ 3
#define WIID_CASHSHOP_BUYLIST_UP			(WIID_CASHSHOP + 849)
#define WIID_CASHSHOP_BUYLIST_DOWN			(WIID_CASHSHOP + 850)
#define WIID_CASHSHOP_BUYLIST_MY_OZ_TEXT	(WIID_CASHSHOP + 851)
#define WIID_CASHSHOP_BUYLIST_MY_OZ			(WIID_CASHSHOP + 852)
#define WIID_CASHSHOP_BUYLIST_MY_OZ_ICON	(WIID_CASHSHOP + 852)
#define WIID_CASHSHOP_BUYLIST_USE_OZ_TEXT	(WIID_CASHSHOP + 854)
#define WIID_CASHSHOP_BUYLIST_USE_OZ		(WIID_CASHSHOP + 855)
#define WIID_CASHSHOP_BUYLIST_USE_OZ_ICON	(WIID_CASHSHOP + 856)
#define WIID_CASHSHOP_BUYLIST_AF_MY_OZ_TEXT	(WIID_CASHSHOP + 857)
#define WIID_CASHSHOP_BUYLIST_AF_MY_OZ		(WIID_CASHSHOP + 858)
#define WIID_CASHSHOP_BUYLIST_AF_MY_OZ_ICON	(WIID_CASHSHOP + 859)
#define WIID_CASHSHOP_BUYLIST_OK			(WIID_CASHSHOP + 860)
#define WIID_CASHSHOP_BUYLIST_CANCEL		(WIID_CASHSHOP + 861)
#define WIID_CASHSHOP_BUYLIST_ITEM_BG		(WIID_CASHSHOP + 862)
#define WIID_CASHSHOP_BUYLIST_TIP			(WIID_CASHSHOP + 863)

//查看
#define WIID_CASHSHOP_WEARLIST					(WIID_CASHSHOP + 880)
#define WIID_CASHSHOP_WEARLIST_ITEMBG			(WIID_CASHSHOP + 885)   //+ 5
#define WIID_CASHSHOP_WEARLIST_ITEM_CHECK		(WIID_CASHSHOP + 890)   //+ 5
#define WIID_CASHSHOP_WEARLIST_ITEM_SLOT		(WIID_CASHSHOP + 895)   //+ 5
#define WIID_CASHSHOP_WEARLIST_ITEM				(WIID_CASHSHOP + 900)   //+ 5
#define WIID_CASHSHOP_WEARLIST_NAME				(WIID_CASHSHOP + 905)   //+ 5
#define WIID_CASHSHOP_WEARLIST_PRICE_BG			(WIID_CASHSHOP + 910)	//+ 5
#define WIID_CASHSHOP_WEARLIST_OZ_ICON			(WIID_CASHSHOP + 915)	//+ 5
#define WIID_CASHSHOP_WEARLIST_PRICE			(WIID_CASHSHOP + 920)	//+ 5
#define WIID_CASHSHOP_WEARLIST_UP				(WIID_CASHSHOP + 925)
#define WIID_CASHSHOP_WEARLIST_DOWN				(WIID_CASHSHOP + 926)
#define WIID_CASHSHOP_WEARLIST_AF_OZ_TEXT		(WIID_CASHSHOP + 927)
#define WIID_CASHSHOP_WEARLIST_AF_COUNT			(WIID_CASHSHOP + 928)
#define WIID_CASHSHOP_WEARLIST_AF_PRICE			(WIID_CASHSHOP + 929)
#define WIID_CASHSHOP_WEARLIST_AF_OZ_ICON		(WIID_CASHSHOP + 930)
#define WIID_CASHSHOP_WEARLIST_OK				(WIID_CASHSHOP + 931)
#define WIID_CASHSHOP_WEARLIST_ITEM_BG			(WIID_CASHSHOP + 932)
#define WIID_CASHSHOP_WEARLIST_TIP				(WIID_CASHSHOP + 933)

//批量索取
#define WIID_CASHSHOP_EXACTLIST					(WIID_CASHSHOP + 940)
#define WIID_CASHSHOP_EXACTLIST_ITEMBG			(WIID_CASHSHOP + 945)   //+ 3
#define WIID_CASHSHOP_EXACTLIST_ITEM_CHECK		(WIID_CASHSHOP + 948)   //+ 3
#define WIID_CASHSHOP_EXACTLIST_ITEM_SLOT		(WIID_CASHSHOP + 951)   //+ 3
#define WIID_CASHSHOP_EXACTLIST_ITEM			(WIID_CASHSHOP + 954)   //+ 3
#define WIID_CASHSHOP_EXACTLIST_NAME			(WIID_CASHSHOP + 957)   //+ 3
#define WIID_CASHSHOP_EXACTLIST_PRICE_BG		(WIID_CASHSHOP + 960)	//+ 3
#define WIID_CASHSHOP_EXACTLIST_OZ_ICON			(WIID_CASHSHOP + 963)	//+ 3
#define WIID_CASHSHOP_EXACTLIST_PRICE			(WIID_CASHSHOP + 966)	//+ 3
#define WIID_CASHSHOP_EXACTLIST_UP				(WIID_CASHSHOP + 969)
#define WIID_CASHSHOP_EXACTLIST_DOWN			(WIID_CASHSHOP + 970)
#define WIID_CASHSHOP_EXACTLIST_MESSAGE_GRN_BG	(WIID_CASHSHOP + 971)
#define WIID_CASHSHOP_EXACTLIST_RECEIVE_IMG		(WIID_CASHSHOP + 972)
#define WIID_CASHSHOP_EXACTLIST_MESSAGE_IMG		(WIID_CASHSHOP + 973)
#define WIID_CASHSHOP_EXACTLIST_RECEIVE_BG		(WIID_CASHSHOP + 974)
#define WIID_CASHSHOP_EXACTLIST_MESSAGE_BG		(WIID_CASHSHOP + 975)
#define WIID_CASHSHOP_EXACTLIST_MESSAGE			(WIID_CASHSHOP + 976)
#define WIID_CASHSHOP_EXACTLIST_RECEIVE			(WIID_CASHSHOP + 977)
#define WIID_CASHSHOP_EXACTLIST_FRIEND_BTN		(WIID_CASHSHOP + 978)
#define WIID_CASHSHOP_EXACTLIST_FRIEND			(WIID_CASHSHOP + 979)
#define WIID_CASHSHOP_EXACTLIST_FRIEND_LIST_BG	(WIID_CASHSHOP + 980)
#define WIID_CASHSHOP_EXACTLIST_FRIEND_LIST		(WIID_CASHSHOP + 981)
#define WIID_CASHSHOP_EXACTLIST_USE_OZ_TEXT		(WIID_CASHSHOP + 984)
#define WIID_CASHSHOP_EXACTLIST_USE_OZ			(WIID_CASHSHOP + 985)
#define WIID_CASHSHOP_EXACTLIST_USE_OZ_ICON		(WIID_CASHSHOP + 986)
#define WIID_CASHSHOP_EXACTLIST_TEXT			(WIID_CASHSHOP + 987)
#define WIID_CASHSHOP_EXACTLIST_OK				(WIID_CASHSHOP + 988)
#define WIID_CASHSHOP_EXACTLIST_CANCEL			(WIID_CASHSHOP + 989)
#define WIID_CASHSHOP_EXACTLIST_TIP				(WIID_CASHSHOP + 990)



#define OZ_INVENSLOT_MAX		80
#define OZ_INVENWEAR_MAX		40
#define COUPON_NUM				16

//------------------------------------------------------------------------------------
enum CASHSHOP_BUY_TYPE
{
	TYPE_BUY = 0,
	TYPE_GIFT = 1,
	TYPE_EXACT = 2,
};

enum CASHSHOP_STORE_TAB
{
	CST_NULL = 0,
	CST_EVENT =1,
	CST_FASSION,
	CST_PET,
	CST_ETC,
	CST_PACKAGE,
	CST_SEARCH,
	CST_HELP,
	CST_POINT,

	CST_MAX,
};

struct CASHSHOP_HELP_INFO
{
	RECT rcTextDst;
	D3DXCOLOR Color;
	std::string strText;
	SPFont* pFont;

	RECT rcImageDst;
	RECT rcImageSrc;
	SPTexture* pkTexture;

	CASHSHOP_HELP_INFO()
	{
		pkTexture = NULL;
		pFont = NULL;
	}

	void Clear()
	{
		SAFE_RELEASE(pkTexture);
		pFont = NULL;
	}
};

//------------------------------------------------------------------------------------
class SPWindow;
class SPPlayer;
class SPPet;
class SPItem;
struct SPCashItemAttr;

class SPWindowCashShop : public SPWindow
{
public:
	SPWindowCashShop(WND_ID WndClassID, INSTANCE_ID InstanceID);
	SPWindowCashShop(INSTANCE_ID InstanceID, int iX, int iY, int iCX, int iCY, SPWindow* pParent = NULL);
	virtual ~SPWindowCashShop();

	virtual void Init();
	virtual void Clean();

	virtual void Process(float fTime);
	virtual void Render(float fTime);

	virtual void Show(bool bWithChild = true);

protected:

	SPIMESSAGE_OBJ_MAP_DECLARE()
	
	virtual int PerformMouseMove(int iX, int iY) ;  //[xialin 2008/08/11]add

	virtual int OnLButtonUpCheck(WPARAM wParam, LPARAM lParam);
	virtual int OnExit(WPARAM wParam, LPARAM lParam);
	virtual int OnErrorOK(WPARAM wParam, LPARAM lParam);

	virtual int OnMyInfoFilling(WPARAM wParam, LPARAM lParam);
	virtual int OnMyInfoUpdate(WPARAM wParam, LPARAM lParam);
	virtual int OnMyInfoCoupon(WPARAM wParam, LPARAM lParam);
	
	virtual int OnItemInvenUp(WPARAM wParam, LPARAM lParam);
	virtual int OnItemInvenDown(WPARAM wParam, LPARAM lParam);
	virtual int OnSetItemInvenUp(WPARAM wParam, LPARAM lParam);
	virtual int OnSetItemInvenDown(WPARAM wParam, LPARAM lParam);
	virtual int OnSetItemInvenCurPage(WPARAM wParam, LPARAM lParam);
	virtual int OnItemInvenCursorMove(WPARAM wParam, LPARAM lParam);
	virtual int OnItemInvenLButtonDown(WPARAM wParam, LPARAM lParam);
	virtual int OnItemInvenLButtonUp(WPARAM wParam, LPARAM lParam);

	//[xialin 2008/07/21] add
	virtual int OnOZInvenUp(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenDown(WPARAM wParam, LPARAM lParam);
	virtual int OnSetOZInvenUp(WPARAM wParam, LPARAM lParam);
	virtual int OnSetOZInvenDown(WPARAM wParam, LPARAM lParam);
	virtual int OnSetOZInvenCurPage(WPARAM wParam, LPARAM lParam);

	virtual int OnOZInvenLeftPage(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenRightPage(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenCursorMove(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenLButtonDown(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenLButtonUp(WPARAM wParam, LPARAM lParam);
	virtual int OnOZSellCursorEnter(WPARAM wParam, LPARAM lParam);
	virtual int OnOZSellCursorOut(WPARAM wParam, LPARAM lParam);
	virtual int OnOZSellLButtonUp(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenSell(WPARAM wParam, LPARAM lParam);
	virtual int OnOZSellHelpLButtonUp(WPARAM wParam, LPARAM lParam);
	
	virtual int OnStorePage(WPARAM wParam, LPARAM lParam);
	virtual int OnChangeSortGender(WPARAM wParam, LPARAM lParam);
	virtual int OnChangeSortPrice(WPARAM wParam, LPARAM lParam);
	
	virtual int OnCashierPlus(WPARAM wParam, LPARAM lParam);
	virtual int OnCashierMinus(WPARAM wParam, LPARAM lParam);
	virtual int OnCashierOK(WPARAM wParam, LPARAM lParam);
	virtual int OnCashierCancel(WPARAM wParam, LPARAM lParam);
	virtual int OnCashierMileageChange(WPARAM wParam, LPARAM lParam);

	virtual int OnGiftPlus(WPARAM wParam, LPARAM lParam);
	virtual int OnGiftMinus(WPARAM wParam, LPARAM lParam);
	virtual int OnGiftOK(WPARAM wParam, LPARAM lParam);
	virtual int OnGiftCancel(WPARAM wParam, LPARAM lParam);
	virtual int OnGiftFriend(WPARAM wParam, LPARAM lParam);
	virtual int OnGiftFriendListLButton(WPARAM wParam, LPARAM lParam);
	virtual int OnGiftFriendListDBLButton(WPARAM wParam, LPARAM lParam);
	virtual int OnGiftMileageChange(WPARAM wParam, LPARAM lParam);

	//[xialin 2008/07/10] 索取功能
	virtual int OnExactOK(WPARAM wParam, LPARAM lParam);
	virtual int OnExactCancel(WPARAM wParam, LPARAM lParam);
	virtual int OnExactFriend(WPARAM wParam, LPARAM lParam);
	virtual int OnExactFriendListLButton(WPARAM wParam, LPARAM lParam);
	virtual int OnExactFriendListDBLButton(WPARAM wParam, LPARAM lParam);
	virtual int OnExactListFriendListLButton(WPARAM wParam, LPARAM lParam);
	virtual int OnExactListFriendListDBLButton(WPARAM wParam, LPARAM lParam);

	//[xialin 2008/07/17] 搜索功能
	virtual int OnSearch(WPARAM wParam, LPARAM lParam);

	virtual int OnSellOK(WPARAM wParam, LPARAM lParam);
	virtual int OnSellCancel(WPARAM wParam, LPARAM lParam);
	virtual int OnSellToolTipEnter(WPARAM wParam, LPARAM lParam);
	virtual int OnSellToolTipOut(WPARAM wParam, LPARAM lParam);
	virtual int OnSellToolTipMove(WPARAM wParam, LPARAM lParam);

	virtual int OnCouponOK(WPARAM wParam, LPARAM lParam);
	virtual int OnCouponCancel(WPARAM wParam, LPARAM lParam);

	virtual int OnResultOK(WPARAM wParam, LPARAM lParam);

	virtual int OnPreViewInvenLeftPage(WPARAM wParam, LPARAM lParam);
	virtual int OnPreViewInvenRightPage(WPARAM wParam, LPARAM lParam);
	virtual int OnPreViewInvenLButtonDown(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPreViewInvenDel(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPreViewInvenInit(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPreViewInvenBuy(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPreViewInvenNormal(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPreViewInvenRun(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPreViewInvenLadder(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPreViewInvenCharInit(WPARAM wParam, LPARAM lParam);

	virtual int OnSetPlayerViewBuy(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPlayerViewExact(WPARAM wParam, LPARAM lParam);
	virtual int OnSetPlayerViewWearInfo(WPARAM wParam, LPARAM lParam);
	
	virtual int OnInvenCategory(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenCategory(unsigned int iID, WPARAM wParam, LPARAM lParam); //[zialin 2008/07/21] add
	virtual int OnStoreTabType(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreCategory1(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreCategory2(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreLButtonDown(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreLButtonDBL(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreBuy(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnCashSortBuy( unsigned int iID, WPARAM wParam, LPARAM lParam );
	virtual int OnStoreGift(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreExact(unsigned int iID, WPARAM wParam, LPARAM lParam);  //[xialin 2008/07/10] 索要功能
	virtual int OnStoreCart(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreCartDel(unsigned int iID, WPARAM wParam, LPARAM lParam);

	virtual int OnBuyListCheck(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnExactListCheck(unsigned int iID, WPARAM wParam, LPARAM lParam);
	virtual int OnChangePlayerViewBack(unsigned int iID, WPARAM wParam, LPARAM lParam);

	//[xialin 2008/08/01] 批量处理
	virtual int  OnBuyListOK(WPARAM wParam, LPARAM lParam);
	virtual int  OnBuyListCancel(WPARAM wParam, LPARAM lParam);
	virtual int  OnWearListOK(WPARAM wParam, LPARAM lParam);
	virtual int  OnExactListOK(WPARAM wParam, LPARAM lParam);
	virtual int  OnExactListCancel(WPARAM wParam, LPARAM lParam);
	virtual int  OnBuyListUp(WPARAM wParam, LPARAM lParam);
	virtual int  OnBuyListDown(WPARAM wParam, LPARAM lParam);
	virtual int  OnWearListUp(WPARAM wParam, LPARAM lParam);
	virtual int  OnWearListDown(WPARAM wParam, LPARAM lParam);
	virtual int  OnExactListUp(WPARAM wParam, LPARAM lParam);
	virtual int  OnExactListDown(WPARAM wParam, LPARAM lParam);
	virtual int	 OnExactListFriend(WPARAM wParam, LPARAM lParam);

	//[xialin 2008/07/17] add
	virtual int OnAddParcel(WPARAM wParam, LPARAM lParam);
	virtual int OnAddConsume(WPARAM wParam, LPARAM lParam);
	virtual int OnAddETC(WPARAM wParam, LPARAM lParam);
	virtual int OnAddEvent(WPARAM wParam, LPARAM lParam);
	virtual int OnAddPET(WPARAM wParam, LPARAM lParam);
	virtual int OnAddWH(WPARAM wParam, LPARAM lParam);
	virtual int OnAddParcel2(WPARAM wParam, LPARAM lParam);
	virtual int OnAddConsume2(WPARAM wParam, LPARAM lParam);
	virtual int OnAddETC2(WPARAM wParam, LPARAM lParam);
	virtual int OnAddEvent2(WPARAM wParam, LPARAM lParam);
	virtual int OnAddPET2(WPARAM wParam, LPARAM lParam);
	virtual int OnAddWH2(WPARAM wParam, LPARAM lParam);
	
	virtual int OnItemInvenToolTipEnter(WPARAM wParam, LPARAM lParam);
	virtual int OnItemInvenToolTipOut(WPARAM wParam, LPARAM lParam);
	virtual int OnItemInvenToolTipMove(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenToolTipEnter(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenToolTipOut(WPARAM wParam, LPARAM lParam);
	virtual int OnOZInvenToolTipMove(WPARAM wParam, LPARAM lParam);
	virtual int OnPreViewToolTipEnter(WPARAM wParam, LPARAM lParam);
	virtual int OnPreViewToolTipOut(WPARAM wParam, LPARAM lParam);
	virtual int OnPreViewToolTipMove(WPARAM wParam, LPARAM lParam);
	virtual int OnCashierToolTipEnter(WPARAM wParam, LPARAM lParam);
	virtual int OnCashierToolTipOut(WPARAM wParam, LPARAM lParam);
	virtual int OnCashierToolTipMove(WPARAM wParam, LPARAM lParam);

	virtual int OnStoreToolTipEnter(unsigned int uiID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreToolTipOut(unsigned int uiID, WPARAM wParam, LPARAM lParam);
	virtual int OnStoreToolTipMove(unsigned int uiID, WPARAM wParam, LPARAM lParam);

	virtual int OnCashSortToolTipEnter( unsigned int uiID, WPARAM wParam, LPARAM lParam );
	virtual int OnCashSortToolTipOut( unsigned int uiID, WPARAM wParam, LPARAM lParam );
	virtual int OnCashSortToolTipMove( unsigned int uiID, WPARAM wParam, LPARAM lParam );

	virtual int OnStoreSultItem(unsigned int uiID, WPARAM wParam, LPARAM lParam);
	virtual int OnExitSultView(WPARAM wParam, LPARAM lParam);

	virtual int OnResultToolTipEnter(WPARAM wParam, LPARAM lParam);
	virtual int OnResultToolTipOut(WPARAM wParam, LPARAM lParam);
	virtual int OnResultToolTipMove(WPARAM wParam, LPARAM lParam);

	virtual int OnClearDrag(WPARAM wParam, LPARAM lParam);
	virtual int OnReflashItemInven(WPARAM wParam, LPARAM lParam);
	virtual int OnInfo(WPARAM wParam, LPARAM lParam);
	virtual int OnUpdate(WPARAM wParam, LPARAM lParam);
	virtual int OnBuy(WPARAM wParam, LPARAM lParam);
	virtual int OnGift(WPARAM wParam, LPARAM lParam);
	virtual int OnExact(WPARAM wParam, LPARAM lParam);  //[xialin 2008/08/04] add
	virtual int OnParcel(WPARAM wParam, LPARAM lParam); //[xialin 2008/07/04] add
	virtual int OnSell(WPARAM wParam, LPARAM lParam);
	virtual int OnCoupon(WPARAM wParam, LPARAM lParam);
	virtual int OnCartList(WPARAM wParam, LPARAM lParam);
	virtual int OnCartAdd(WPARAM wParam, LPARAM lParam);
	virtual int OnCartDel(WPARAM wParam, LPARAM lParam);
	virtual int OnHidePopupMenu(WPARAM wParam, LPARAM lParam);
	virtual int OnSetFillingURL(WPARAM wParam, LPARAM lParam);
	virtual int OnNeedItemUpdate(WPARAM wParam, LPARAM lParam);

	virtual int OnGetPlayer(WPARAM wParam, LPARAM lParam);
	virtual int OnSwapTerrainMgr(WPARAM wParam, LPARAM lParam);
	virtual int OnUpdateCashSort( WPARAM wParam, LPARAM lParam );

	bool Buy();
	bool Gift();

	bool IsBuyCashItemList(SPCashItemAttr * pCashItemAttr);

	int OnCheckCart(WPARAM wParam, LPARAM lParam);	

	void ProcessHotKey(float fTime);
	void ProcessNoticeRandom(float fTime);
	void ProcessAni(float fTime);
	void ProcessBuyWaitAni(float fTime);
	void ProcessSellHelp(float fTime);
	void ProcessWebbrowser(float fTime);

	void InitMyInfo();
	void InitItemInven();
	void InitOzInven();
	void InitChar();
	void InitStore();
	void InitPrevView();
	void InitCashierDlg();
	void InitGiftDlg();
	void InitExactDlg();				 //[xialin 2008/07/10] 索要对话框
	void InitErrorDlg();
	void InitCouponDlg();
	void InitSellDlg();
	void InitBackground();
	void InitResult();
	void InitBuyWait();
	void InitPlayerView();               //[xialin 2008/07/10] 添加玩家预览视图
	void InitSultListView();             //[xialin 2008/07/10] 添加商品配套提示
	void InitBuyListDlg();               //[xialin 2008/07/10] 批量购买商品
	void InitWearListDlg();              //[xialin 2008/07/10] 查看试穿
	void InitExactListDlg();             //[xialin 2008/07/10] 批量索取

	void RefreshBuyListDlg();
	void RefreshWearListDlg();
	void RefreshExactListDlg();
	
	void InitStorePopup(SPWindow* pkParent);
	void RenderPopup();
	void UpdateMyInfo();

	 //[xialin 2008/07/10] 批量物品状态
	void SetBuyCheck(int iIndex, bool bCheck);
	bool GetBuyCheck(int iIndex);
	int  GetBuyCheckCount();

	SPCashItemAttr * GetBuyListItemByIdx(int iIndex);
	int GetBuyListItemSize();

	void SetItemInvenCategory(int iType);
	void SetOZInvenCategory(int iType);  //[xialin 2008/07/21] add
	void RefreshItemInven();
	SPItem* GetItemInvenItem(int iSlotIndex);
	void EmptyItemInvenSlot();

	void ClearOZInven();
	void UpdateOZInven();
	void SetOZInvenPageText();
	void SetOZSellInfo(SPItem* pItem);
	SPItem* GetOZInvenItem(int iSlotIndex);
	void EraseOZInvenItem(int iSlotIndex);
	
	void SetStoreTabType(CASHSHOP_STORE_TAB eType);
	int SetStoreCashCategory(int iCategory, int iIndex);
	void SetStoreCategory(int iCategory);
	int GetStoreWindowID();
	int ConvertCashCategory();
	void RefreshStore();
	void SetStorePageText();
	void UpdateItemList();
	void CalcPageNum();
	bool RefreshSultListView(SPCashItemAttr* pkItemAttr);
	
	void ShowCashierDlg(SPCashItemAttr* pkItemAttr);
	void ShowGiftDlg(SPCashItemAttr* pkItemAttr);
	void ShowExactDlg(SPCashItemAttr* pkItemAttr);           //[xialin 2008/07/10]   索要功能
	void ShowSellDlg();
	SPCashItemAttr* GetStoreCashItemAttr(int iIndex);
	void CalcCashierMoney(int iOZ, int iMileage);
	void CalcGiftMoney(int iOZ, int iMileage);
	void UpdateFriendList();
	void SetStoreTabWindow(CASHSHOP_STORE_TAB eType);
	void SetStoreToolTipEnter(SPCashItemAttr* pkCashItemAttrm, LPARAM lParam);
	void SetStoreToolTipMove(SPCashItemAttr* pkCashItemAttr, LPARAM lParam);
	void SetStoreToolTipOut(LPARAM lParam);

	void ShowStorePopupMenu(int iID, bool bToggle = false);
	void HideStorePopupMenu(int iID);

	void RefreshPreViewInven();
	void ClearPreViewInven();
	void SetPrevViewInvenPageText();
	bool InsertPreViewInven(int iIndex, SPCashItemAttr* pkItemAttr);
	bool InsertPreViewInven(SPCashItemAttr* pkItemAttr);
	bool IsExistPrevViewInvenItem(SPCashItemAttr* pkItemAttr);
	void ClearPreViewSelect();
	SPCashItemAttr* GetPreViewInvenItem(int iSlotIndex);
	void ResetPlayerLayer();
	void InitPlayerAnimation();
	bool IsEquipPlayerLayer(int iItemID);
	bool IsPetLayer(int iItemID);
	bool IsBugle(int iItemID);      //[xialin 2008/08/14]add
	bool SetEquipPlayerLayer(int iItemID, bool bOff = false);
	bool SetEquipPlayerLayer(SPCashItemAttr* pkCashItemAttr, bool bOff = false); //[xialin 2008/08/04] add
	void SetAniSeq(unsigned int uiAniIndex, bool bLoop = true);
	void SetPlayerDefaultFigureItem();
	FIGURE_ITEM* GetDefaultFigureItem(CONTAINER_TYPE eType, int iSlotIndex);
	FIGURE_ITEM* GetEquipFigureItem(CONTAINER_TYPE eType, int iSlotIndex);
	void InsertEquipFigureItem(FIGURE_ITEM& item);
	void DeleteEquipFigureItem(CONTAINER_TYPE eType, int iSlotIndex, int iItemID);

	//[xialin 2008/08/04] add
	void InsertEquipCashItem(SPCashItemAttr* pkCashItemAttr);
	void DeleteEquipCashItemByItem(SPCashItemAttr* pkCashItemAttr);
	void DeleteSameEquipCashItem(SPCashItemAttr* pkCashItemAttr);
	SPCashItemAttr* GetEquipCashItem(SPCashItemAttr* pkCashItemAttr);

	int SetSliderMaxPage(int iType, int iPage);
	int SetSliderPage(int iType, int iPage);

	void SetSelectSlot(int iSlotIndex, bool bPrevView);

	void ClearSelectItem();

	bool LoadHelpLDTFile();
	void InsertHelpInfo(int iPageNo, CASHSHOP_HELP_INFO* pHelpInfo);
	std::vector< CASHSHOP_HELP_INFO >* GetHelpInfo(int iPageNo);
	void RenderHelpInfo();

	bool LoadDefaultLDTFile();
	int GetDefaultPage(int iIndex);

	void SetErrorDlg(int iError, bool bShowButton = true);
	void SetErrorDlg(const char* pszMsg, bool bShowButton = true);
	void ShowCouponDlg();

	void ShowResultDlg(CASHSHOP_BUY_TYPE BuyType, int iItemID, const char* pszTargetName = NULL);
	void ShowBuyWaitDlg();
	void HideBuyWaitDlg();
	void InitBuyWaitAni(SPWindow* pkParentWindow);

	void ProcessBackground(float fTime);
	void RenderBackground();

	void SetPet(unsigned int uiClassID, int iItemID = 0);
	void ReleasePet();

	void ClearEffectList();
	void AddEffectList(int iItemID, int iUniqueNo, int iEffectID);
	void DeleteEffectList(int IItemID);
	int GetEffectUniqueNo();

	void CaluCashierGlow(int& iPrice);

	void SetCategoryDiable();
	bool IsBuyRequireSuccess(SPCashItemAttr* pkItemAttr);

	struct EVENT_ANIMATION
	{
		float fAccmulateTime;
		float fDelayTime;
		int iTotalFrame;
		int iCurFrame;
		int iIncDir;

		RECT rcDst;
		RECT rcSrc[2];
	};

	struct BACKGROUND_ANIMAITON
	{
		SPVector vCurPos;
		SPVector vStrPos;
		SPVector vEndPos;
		
		float fSpeed;
		float fRotate;

		RECT rcSrc;
	};

protected:
	
	int m_iItemInvenCategory;
	int m_iItemInvenMaxPage[6];
	int m_iItemInvenCurPage[6];

	int m_iOZInvenCategory;
	int m_iOZInvenCurPage[2];
	int m_iOZInvenMaxPage[2];
	SPItem* m_pSellItem;

	CASHSHOP_STORE_TAB m_eStoreTabType;
	int m_iStoreCategory[3];
	int m_iStoreCurPage;
	int m_iStoreMaxPage;
	int m_iSortType[2];
	SPTexture* m_pkEventTexture;
	SPTexture* m_pkSaleArrowTexture;
	SPTexture* m_pkSaleOrderTexture;
	std::vector< EVENT_ANIMATION > m_vEventAnimation;
	std::vector< RECT > m_vSaleArrow;
	std::vector< RECT > m_vSaleOrderArrow;

	int m_iCashierOZ;
	int m_iCashierMileage;
	int m_iCahsierPrice;
	int m_iCashierMileageRange[2];
	RECT m_rcDstBlackBackground;
	RECT m_rcSrcBlackBackground;
	SPTexture* m_pkBlackBackground;
	std::vector<SPCashItemAttr*>  m_vCashierItemAttr; //[xialin 2008/08/01]edit
	std::vector< unsigned int > m_vCartList;

	bool m_bPreViewSelect;
	int m_iPreSelectSlot;
	SPTexture* m_pkPreSelectImage;
	RECT m_rcPreSelect[4];
	EVENT_ANIMATION m_PreSelectAni;

	int m_iPreViewInvenMaxPage;
	int m_iPreViewInvenCurPage;
	std::vector< FIGURE_ITEM > m_vDefaultFigureItem;
	std::vector< FIGURE_ITEM > m_vEquipFigureItem;
	std::vector< SPCashItemAttr* > m_vEquipCashItem;          //[xialin 2008/08/04] add
	std::map< int, SPCashItemAttr* > m_mPreViewInvenItem;

	SPPlayer* m_pkPlayer;
	unsigned int m_uiAniIndex;
	unsigned int m_uiBeforeAniIndex;
	float m_fAniAccmulateTime;
	float m_fAniMaxTime;

	SPPet* m_pkPet;

	RECT m_rcDstBackground[5];
	RECT m_rcSrcBackground[5];
	SPTexture* m_pkBackground;

	GU_ID m_iGUID;
	TCHAR m_szAccountID[MAX_LEN_ID+4];
	unsigned int m_uiCurOZ;
	unsigned int m_uiCurMileage;
	std::string  m_strURLToken ;

	int m_iSelectSlot;
	int m_iSelectInven;
	SPItem* m_pkSelectItem;

	bool m_bHelpTextDraw;	
	std::map< int, std::vector< CASHSHOP_HELP_INFO > > m_mHelpInfoList;

	float m_fNoticeAccmulateTime;
	float m_fNoticeChangeTime;

	int m_iCashierGlowUnit;
	int m_iMileageRatio;
	int m_iMileageGlowUnit;
	SPCashItemAttr* m_pkResultItemAttr;

	bool m_bBuyRecv;
	bool m_bOnceAni;
	float m_fBuyWaitAccmulateTime;
	unsigned int m_uiBuyItem;
	std::string m_strTargetName;
	EVENT_ANIMATION m_BuyAni[14];

	int m_iEffectUniqueNo;
	std::map< int, std::vector< int > > m_mEffectList;

	float m_fSellHelpAccumulate;
	int m_iSellHelpAlpha;

	bool m_bWebbrowerLoadingWait;
	int m_iErrorType;

	SPCashItemAttr * m_pCurSultItemAttr;               //[xialin 2008/08/01]add
	std::vector<bool> m_vecBuyCheck;                   //[xialin 2008/08/01]add
	int               m_iCurStartItem;                 //[xialin 2008/08/01]add
	std::vector<SPCashItemAttr*> m_vecBuyCashItemList; //[xialin 2008/09/19]add

	SPPlayer * m_pkLobbyPlayer;

	CASHSHOP_BUY_TYPE          m_eBuyType;             //[xialin 2008/08/04]add

	std::string                m_strGiftFriendName;		//[xialin 2008/08/05]add
	std::string                m_strGiftFriendMsg;		//[xialin 2008/08/05]add

	SPTerrainManager*		   m_pMgrTerrain[3];		//[xialin 2008/08/05]add
	SPTerrainManager*		   m_gpMgrTerrain;			//[xialin 2008/08/05]add

	std::map< int, int > m_mDefaultPageList;
	std::vector< BACKGROUND_ANIMAITON > m_vBackgroundTextList;
	std::vector< BACKGROUND_ANIMAITON > m_vBackgroundStarList;
};

#endif
