// Copyright (C) metalgeni
//***************************************************************************
// System Name : 
// Comment     : 
// Creation    : metalgeni 2004-08-12 오후 2:32:54 
//***************************************************************************

#pragma once


#ifdef _RES_PATH

	extern TCHAR RES_WORK_RESOURCE_PATH[MAX_PATH];

	// miles redist
	#define RES_MILES_REDIST_PATH					"REDIST" 

#else

	#ifdef _RES_BELOS
	#define RES_WORK_RESOURCE_PATH					"//BELOS/RESOURCE/CLIENT/"
	#elif _RES_ELIAS
	#define RES_WORK_RESOURCE_PATH					"//ELIAS/RESOURCE/CLIENT/"
	#else 
	#define RES_WORK_RESOURCE_PATH					""
	#endif

	// miles redist
	#define RES_MILES_REDIST_PATH					RES_WORK_RESOURCE_PATH "REDIST" 

#endif

#define RES_PAHT_LOADING													"DATA/LOADING/"
#define RES_PATH_BGFORMAT													"DATA/BGFORMAT/"
#define RES_PATH_TERRAIN													"DATA/TERRAIN/"
#define RES_PATH_GLOBAL_TERRAIN												"DATA/GLOBALTERRAIN/" //[2005/6/15] - jinhee Global Terrain Resource Floder

#ifdef _CHARTOOL
#define RES_PATH_CHAR														"DATA/CHAR/SAMPLELAYERV2/"
#else
//#define RES_PATH_CHAR														"DATA/CHAR/SAMPLELAYERV2COMPLETE/"
#define RES_PATH_CHAR														"DATA/CHAR/CHARLAYER/"
#endif																					

#define RES_PATH_MONSTER													"DATA/CHAR/MONSTER/"
#define RES_PATH_NPC														"DATA/CHAR/MONSTER/"

// File Name
#define RES_FNAME 
#define RES_FNAME_TESTBLOCK													"DATA/CURSOR/TESTBLOCK.TGA"
#define RES_FNAME_TESTBLOCKL2												"DATA/CURSOR/TESTBLOCKLAYER2.TGA"

#define RES_FNAME_STAGE														"DATA/BGFORMAT/STAGENEW.TXT"	//JINHEE - [2004/12/31] //test
#define RES_FNAME_STAGE_BINARY												"DATA/BGFORMAT/STAGENEW.STG"	//JINHEE - [2004/12/31] //test
#define RES_FNAME_BGFORMAT													"DATA/BGFORMAT/BGFORMAT.TXT"
#define RES_FNAME_TERRAINPALLET												"DATA/BGFORMAT/TERRAINPALLET.TXT"
#define RES_FNAME_GLOBAL_TERRAINPALLET										"DATA/BGFORMAT/TERRAINPALLET.TXT"	//[2005/6/13] - jinhee
#define RES_FNAME_GLOBAL_TERRAINPALLET_BIN									"DATA/BGFORMAT/TERRAINPALLET.PAL"	//[2005/6/13] - jinhee
#define RES_FNAME_TERRAINFORM												"DATA/BGFORMAT/TERRAINFORM.TXT"
#define RES_FNAME_TERRAINATTRIBUTE											"DATA/BGFORMAT/TERRAINATTRIBUTE.TXT"


#define RES_FNAME_COMMONANITABLE											"DATA/ANITABLE/COMMONANITABLE.TXT"
#define RES_FNAME_COMMONANITABLE2											"DATA/ANITABLE/COMMONANITABLE2.TXT"

#define RES_FNAME_ANITABLE_STAND											"DATA/ANITABLE/ANI_STAND.SEQ"
#define RES_FNAME_ANITABLE_WALK												"DATA/ANITABLE/ANI_WALK.SEQ"
#define RES_FNAME_ANITABLE_JUMP												"DATA/ANITABLE/ANI_JUMP.SEQ"
#define RES_FNAME_ANITABLE_FLY												"DATA/ANITABLE/ANI_FLY.SEQ"
#define RES_FNAME_ANITABLE_ATTACK00											"DATA/ANITABLE/ANI_ATTACK00.SEQ"
#define RES_FNAME_ANITABLE_ATTACK01											"DATA/ANITABLE/ANI_ATTACK01.SEQ"

#define RES_FNAME_ANITABLE_CLIMB_LADDER_UP									"DATA/ANITABLE/ANI_CLIMBLADDERUP.SEQ"
#define RES_FNAME_ANITABLE_CLIMB_LADDER_WAIT								"DATA/ANITABLE/ANI_CLIMBLADDERWAIT.SEQ"
#define RES_FNAME_ANITABLE_CLIMB_LADDER_DOWN								"DATA/ANITABLE/ANI_CLIMBLADDERDOWN.SEQ"

#define RES_FNAME_ANITABLE_CLIMB_ROPE_UP									"DATA/ANITABLE/ANI_CLIMBROPEUP.SEQ"
#define RES_FNAME_ANITABLE_CLIMB_ROPE_WAIT									"DATA/ANITABLE/ANI_CLIMBROPEWAIT.SEQ"
#define RES_FNAME_ANITABLE_CLIMB_ROPE_DOWN									"DATA/ANITABLE/ANI_CLIMBROPEDOWN.SEQ"

#define RES_FNAME_ANITABLE_HANGING_MOVE										"DATA/ANITABLE/ANI_HANGINGMOVE.SEQ"
#define RES_FNAME_ANITABLE_HANGING_WAIT										"DATA/ANITABLE/ANI_HANGINGWAIT.SEQ"

#define RES_FNAME_ANITABLE_MONSTER_STAND									"DATA/ANITABLE/ANI_MOB_STAND.SEQ"
#define RES_FNAME_ANITABLE_MONSTER_WALK										"DATA/ANITABLE/ANI_MOB_WALK.SEQ"
#define RES_FNAME_ANITABLE_MONSTER_ATTACK									"DATA/ANITABLE/ANI_MOB_ATTACK.SEQ"

#define RES_FNAME_CTRL_														"DATA/INTERFACE/"											
#define RES_FNAME_FX														"DATA/FX/"

// LDT File List
#define RES_FNAME_LDT_GLOBAL_RES											"DATA/LDT/GLOBAL_RES.LDT"
#define RES_FNAME_LDT_GLOBAL_STRING											"DATA/LDT/GLOBAL_STRING.LDT"
#define RES_FNAME_LDT_DATA_TABLE											"DATA/LDT/LDT_DBNAME_MAP.LDT"

#define RES_FNAME_LDT_CHAT_COLOR											"DATA/LDT/CHAT_COLOR.LDT"

#define RES_FNAME_LDT_DESC													"DATA/LDT/DESCRIPTIONDATA.LDT"
#define RES_FNAME_LDT_LOGINSERVER_INFO										"DATA/LDT/LOGINSERVERINFO.LDT"
#define RES_FNAME_LDT_MAP_EVENT												"DATA/LDT/MAPEVENT.LDT"
#define RES_FNAME_LDT_MAP_INFO												"DATA/LDT/MAP_INFO.LDT"
#define RES_FNAME_LDT_EVENT_PORTAL											"DATA/LDT/EVENTPORTAL.LDT"
#define RES_FNAME_LDT_ITEM_CLUSTER											"DATA/LDT/ITEM.LDT"
#define RES_FNAME_LDT_ITEM_CLUSTER1											"DATA/LDT/ITEM_1.LDT"
#define RES_FNAME_LDT_ITEM_CLUSTER2											"DATA/LDT/ITEM_2.LDT"
#define RES_FNAME_LDT_ITEM_CLUSTER3											"DATA/LDT/ITEM_3.LDT"
#define RES_FNAME_LDT_SETITEM_1												"DATA/LDT/SETITEM_A.LDT"
#define RES_FNAME_LDT_SETITEM_2												"DATA/LDT/SETITEM.LDT"
#define RES_FNAME_LDT_PVP_ITEM1												"DATA/LDT/PVP_ITEM_1.LDT"

#define RES_FNAME_LDT_ABUSE_LIST											"DATA/LDT/ABUSE_LIST.LDT"
#define RES_FNAME_LDT_BAN_LIST												"DATA/LDT/BAN_LIST.LDT"

#define RES_FNAME_LDT_ITEMSET												"DATA/LDT/ITEMSET.LDT"
#define RES_FNAME_LDT_ITEMSET_1												"DATA/LDT/ITEMSET_A.LDT"
#define RES_FNAME_LDT_ITEMSET_2												"DATA/LDT/ITEMSET_B.LDT"
#define RES_FNAME_LDT_ITEMOPT_KIND_GROUP									"DATA/LDT/OPTION_GROUP.LDT"
#define RES_FNAME_LDT_ITEMOPT_GROUP_LIST									"DATA/LDT/OPTION_GROUP_LIST.LDT"
#define RES_FNAME_LDT_ITEM_OPTION											"DATA/LDT/ITEM_OPTION.LDT"
#define RES_FNAME_LDT_MOBLOOT												"DATA/LDT/MOBLOOT.LDT"

#define RES_FNAME_LDT_FXLIST												"DATA/LDT/FX_LIST.LDT"
#define RES_FNAME_LDT_FXGROUP												"DATA/LDT/FX_GROUP.LDT"
#define RES_FNAME_LDT_FXUNIT												"DATA/LDT/FX_UNIT.LDT"


#define RES_FNAME_LDT_CREATEAVATAR											"DATA/LDT/CREATEAVATAR.LDT"
#define RES_FNAME_LDT_CREATION_INFO											"DATA/LDT/CREATION_INFO.LDT"	



#define RES_FNAME_LDT_LOAD													"DATA/LDT/LOADING_IMAGE.LDT"

#define RES_FNAME_LDT_NPC													"DATA/LDT/NPC.LDT"
#define RES_FNAME_LDT_NPCTALK												"DATA/LDT/NPCTALK.LDT"
#define RES_FNAME_LDT_NPCTRADE												"DATA/LDT/NPCTRADE.LDT"
#define RES_FNAME_LDT_NPCTRADE_DETAIL										"DATA/LDT/NPCTRADE_DETAIL.LDT"
#define RES_FNAME_LDT_NPCSTORAGE											"DATA/LDT/NPC_STORAGE.LDT"
#define RES_FNAME_LDT_NPCPORTAL												"DATA/LDT/NPC_PORTAL.LDT"
#define RES_FNAME_LDT_PORTAL_DETAIL											"DATA/LDT/PORTAL_DETAIL.LDT"
#define RES_FNAME_LDT_NPCEVENT_LIST											"DATA/LDT/NPC_EVENT_LIST.LDT"
#define RES_FNAME_LDT_NPCEVENT												"DATA/LDT/NPC_EVENT.LDT"
#define RES_FNAME_LDT_NPCEVENT_DETAIL										"DATA/LDT/NPC_EVENT_DETAIL.LDT"
#define RES_FNAME_LDT_SAVEPOINT												"DATA/LDT/SAVEPOINT.LDT"
#define RES_FNAME_LDT_NPCQUEST												"DATA/LDT/QUEST_LIST.LDT"
#define RES_FNAME_LDT_QUEST													"DATA/LDT/QUEST.LDT"
#define RES_FNAME_LDT_QUEST_REWARD											"DATA/LDT/QUEST_REWARD.LDT"
#define RES_FNAME_LDT_GIFT													"DATA/LDT/GIFT_INFO.LDT"
#define RES_FNAME_LDT_NPCGIFT												"DATA/LDT/NPC_GIFT.LDT"
#define RES_FNAME_LDT_NPCGUILD												"DATA/LDT/NPC_GUILD.LDT"
#define RES_FNAME_LDT_CUTIN_TALK											"DATA/LDT/CUTIN_TALK.LDT"
#define RES_FNAME_LDT_MOBBASE												"DATA/LDT/MOBBASE.LDT"
#define RES_FNAME_LDT_MOBARRANGE											"DATA/LDT/MOBARRANGE.LDT"
#define RES_FNAME_LDT_MOBAI													"DATA/LDT/MOB_ACTION.LDT"
#define RES_FNAME_LDT_MOBAI_ATTACK											"DATA/LDT/MOB_ATTACK_AI.LDT"

#define RES_FNAME_LDT_EXPERIENCE											"DATA/LDT/EXPERIENCE.LDT"
#define RES_FNAME_LDT_STATUS_LEVEL											"DATA/LDT/STATUS_LEVEL.LDT"
#define RES_FNAME_LDT_PVP_STATUS											"DATA/LDT/PVP_STATUS.LDT"
#define RES_FNAME_LDT_EFFECT												"DATA/LDT/EFFECT.LDT"
#define RES_FNAME_LDT_PVP_EFFECT											"DATA/LDT/PVP_EFFECT.LDT"
#define RES_FNAME_LDT_SKILL													"DATA/LDT/SKILL.LDT"
#define RES_FNAME_LDT_PVP_SKILL												"DATA/LDT/PVP_SKILL.LDT"
#define RES_FNAME_LDT_MOTION_STATUS											"DATA/LDT/MOTION_STATUS.LDT"
#define RES_FNAME_LDT_PVP_MOTION_STATUS										"DATA/LDT/PVP_MOTION_STATUS.LDT"
#define RES_FNAME_LDT_MOB_MOTION_STATUS										"DATA/LDT/MOB_MOTIONSTATUS.LDT"
#define RES_FNAME_LDT_KNOCKBACK												"DATA/LDT/BEATTACKED.LDT"
#define RES_FNAME_LDT_TITLEINFO												"DATA/LDT/TITLE.LDT"
#define RES_FNAME_LDT_QUESTINFO												"DATA/LDT/QUEST.LDT"
#define RES_FNAME_LDT_QUESTREWARDINFO										"DATA/LDT/QUEST_REWARD.LDT"
#define RES_FNAME_LDT_QUESTGROUP											"DATA/LDT/QUEST_LIST.LDT"
#define RES_FNAME_LDT_MOBLVFACTOR											"DATA/LDT/MOB_LV_FACTOR.LDT"
#define RES_FNAME_LDT_TEAMFACTOR											"DATA/LDT/TEAM_FACTOR.LDT"
#define RES_FNAME_LDT_TEAMLVFACTOR											"DATA/LDT/TEAM_LV_FACTOR.LDT"
#define RES_FNAME_LDT_LOGINEVENT											"DATA/LDT/LOGIN_EVENT.LDT"
#define RES_FNAME_LDT_CHATCOMMAND											"DATA/LDT/CHAT_COMMAND.LDT"
#define RES_FNAME_LDT_CHATTYPE												"DATA/LDT/CHAT_TYPE.LDT"
#define RES_FNAME_LDT_CHATADVERTISEMENT										"DATA/LDT/NOTICE_RANDOM.LDT"

#define RES_FNAME_LDT_UITOOLTIP												"DATA/LDT/UI_TOOLTIP.LDT"
#define RES_FNAME_LDT_HELP_MENU												"DATA/LDT/HELP_MENU.LDT"
#define RES_FNAME_LDT_HELP_CONTENT											"DATA/LDT/HELP_CONTENT.LDT"

#define RES_FNAME_LDT_TITLE													"DATA/LDT/TITLE.LDT"
#define RES_FNAME_LDT_CASHSHOP												"DATA/LDT/CASH_SHOP.LDT"
#define RES_FNAME_LDT_CASHSHOP_MINOR										"DATA/LDT/CASH_SHOP1.LDT"
#define RES_FNAME_LDT_CASHSHOP_HOT											"DATA/LDT/CASH_SHOP_HOT.LDT"
#define RES_FNAME_LDT_BEAUTYSHOP											"DATA/LDT/BEAUTY_SHOP.LDT"
#define RES_FNAME_LDT_WORLD_MAP_STAGE										"DATA/LDT/WORLD_MAP_STAGE.LDT"
#define RES_FNAME_LDT_WORLD_MAP_GROUP										"DATA/LDT/WORLD_MAP_GROUP.LDT"

#define RES_FNAME_LDT_ITEM_ENCHANT											"DATA/LDT/ITEM_ENCHANT.LDT"
#define RES_FNAME_LDT_ITEM_UPGRADE											"DATA/LDT/ITEM_UPGRADE.LDT"
#define RES_FNAME_LDT_ITEM_TIMEADD											"DATA/LDT/ITEM_ADD_TIME.LDT"
#define RES_FNAME_LDT_PET_TALK												"DATA/LDT/PET_TALK.LDT"
#define RES_FNAME_LDT_ITEM_MIX												"DATA/LDT/ITEM_CREATE_RECIPE.LDT"
#define RES_FNAME_LDT_ITEM_MIX_EXP											"DATA/LDT/ITEM_CREATE_LV.LDT"


#define RES_FNAME_LDT_QUEST_DROP_ITEM										"DATA/LDT/QUEST_DROP_ITEM.LDT"

#define RES_FNAME_LDT_USER_SHOP												"DATA/LDT/PRIVATE_STORE.LDT"
#define RES_FNAME_LDT_WAY_POINT												"DATA/LDT/WAY_POINT.LDT"
#define RES_FNAME_LDT_ITEMADDTIMEINFO										"DATA/LDT/ITEM_ADD_TIME.LDT"

#define RES_FNAME_LDT_SKILL_MAIN_MENU										"DATA/LDT/SKILL_MAIN_MENU.LDT"
#define RES_FNAME_LDT_SKILL_SUB_MENU										"DATA/LDT/SKILL_SUB_MENU.LDT"
#define RES_FNAME_LDT_SKILL_CONTENT											"DATA/LDT/SKILL_CONTENT.LDT"
#define RES_FNAME_LDT_SKILL_TREESETTING										"DATA/LDT/SKILL_TREE_SETTING.LDT"
#define RES_FNAME_LDT_SKILL_LEARN											"DATA/LDT/LEARN_SKILL.LDT"

#define RES_FNAME_LDT_LOCALIZE												"DATA/LDT/LOCALIZE.LDT"
#define RES_FNAME_LDT_GLOBAL_SYS											"DATA/LDT/GLOBAL_SYS.LDT"
#define RES_FNAME_LDT_GUILDINFO												"DATA/LDT/GUILD.LDT"
#define RES_FNAME_LDT_INDUNINFO												"DATA/LDT/INDUN.LDT"
#define RES_FNAME_LDT_PRIZE													"DATA/LDT/PRIZE.LDT"
#define RES_FNAME_LDT_GUILDAUTHORITYINFO									"DATA/LDT/GUILD_AUTHORITY.LDT"
#define RES_FNAME_LDT_CROPINFO												"DATA/LDT/CROP.LDT"
#define RES_FNAME_LDT_DIVISIONINFO											"DATA/LDT/DIVISION.LDT"
#define RES_FNAME_LDT_BOOSTERINFO											"DATA/LDT/BOOSTER.LDT"
#define RES_FNAME_LDT_INDUNMISSIONINFO										"DATA/LDT/INDUN_MISSION.LDT"
#define RES_FNAME_LDT_RECALLINFO											"DATA/LDT/RECALL.LDT"
#define RES_FNAME_LDT_GUILDMARKINFO											"DATA/LDT/GUILD_CI.LDT"
#define RES_FNAME_LDT_GAMBLE												"DATA/LDT/GAMBLE.LDT"
#define RES_FNAME_LDT_GAMBLE_REWARD											"DATA/LDT/GAMBLE_REWARD.LDT"
#define RES_FNAME_LDT_CHANGE_CLASS											"DATA/LDT/CLASS_CHANGE.LDT"
#define RES_FNAME_LDT_CHANGE_CLASS_EFFECT									"DATA/LDT/CLASS_EFFECT.LDT"
#define RES_FNAME_LDT_LEVEL_UP_EFFECT										"DATA/LDT/LEVEL_UP_EVENT.LDT"
#define RES_FNAME_LDT_PVPINDUNINFO											"DATA/LDT/PVP_INDUN.LDT"
#define RES_FNAME_LDT_PVPDIVISIONINFO										"DATA/LDT/PVP_DIVISION.LDT"
#define RES_FNAME_LDT_PVPMATCHINFO											"DATA/LDT/TEAM_MATCHING.LDT"
#define RES_FNAME_LDT_PVPGLORYLEVEL											"DATA/LDT/GLORY_LEVEL.LDT"
#define RES_FNAME_LDT_PVPPOINTINFO											"DATA/LDT/PVP_POINT.LDT"
#define RES_FNAME_LDT_GLOBALEVENTINFO										"DATA/LDT/GLOBAL_EVENT.LDT"

#define RES_FNAME_LDT_EVENT_CORE_START										"DATA/LDT/CP_EVENT_START.LDT"
#define RES_FNAME_LDT_EVENT_CORE_REQUIRE									"DATA/LDT/CP_EVENT_REQUIRE.LDT"
#define RES_FNAME_LDT_EVENT_CORE_MISSION									"DATA/LDT/CP_EVENT_MISSION.LDT"
#define RES_FNAME_LDT_EVENT_ATTACH_IMAGE									"DATA/LDT/CP_IMAGE.LDT"	

//20071119 mijin 강제이벤트 description
#define RES_FNAME_LDT_EVENT_MISSION_DESC									"DATA/LDT/FLAG_INFO.LDT"

#define RES_FNAME_LDT_GUIDE_BOOK											"DATA/LDT/GUIDE_BOOK.LDT"

#define RES_FNAME_LDT_MY_STYLE												"DATA/LDT/TALKROOM_STYLE.LDT"
#define RES_FNAME_LDT_ROOM_STYLE											"DATA/LDT/TALKROOM_ROOMSTYLE.LDT"
#define RES_FNAME_LDT_AUTO_SUBJECT											"DATA/LDT/TALKROOM_AUTOSUBJECT.LDT"

#define RES_FNAME_LDT_AUCTION_TYPE											"DATA/LDT/AUCTION_TYPE.LDT"

#define RES_FNAME_LDT_LOVE_LEVEL											"DATA/LDT/LOVE_LEVEL.LDT"

// Stream ID 
#define RES_FID_TEST_STREAM													"DATA/OUT2.SPF" 

// UserInterface.
#define RES_FNAME_XML_UI													"DATA/INTERFACE/UI/UI.XML" // 08.06.26[W.Fairy]
#define RES_FNAME_XML_UI_STATUS												"DATA/INTERFACE/UI/UI_STATUS.xml"		// 
#define RES_FNAME_XML_UI_PLAYERINFO											"DATA/INTERFACE/UI/UI_PLAYERINFO.xml"	// 
#define RES_FNAME_XML_UI_CMDRING_MENU										"DATA/INTERFACE/UI/UI_CMDRING_MENU.xml" // 
#define RES_FNAME_XML_UI_LOVE												"DATA/INTERFACE/UI/UI_LOVE.xml"			//
#define RES_FNAME_XML_UI_PET_SERVICE										"DATA/INTERFACE/UI/UI_PET_SERVICE.xml"  //
#define RES_FNAME_XML_UI_LOVEMSG											"DATA/INTERFACE/UI/UI_LOVEMSG.xml"      //
#define RES_FNAME_XML_UI_OPTIONRST											"DATA/INTERFACE/UI/UI_OPTIONRST.xml"	// [2008/10/17] - 옵션 재분배.
#define RES_FNAME_XML_UI_RANKING											"DATA/INTERFACE/UI/UI_RANKING.xml"		// [2008/10/27] - 랭킹.
#define RES_FNAME_XML_UI_SAMPLE												"DATA/INTERFACE/UI/UI_SAMPLE.xml"		// 새로운 UI를 위한 샘플 화일. 추후 삭제 요망..

// bugle types ldt
#define RES_BUGLE_TYPE														"DATA/LDT/BUGLE.LDT"
// effect item upgrade ldt
#define RES_EFFECT_ITEM_UPGRADE												"DATA/LDT/EFFECTITEMUPGRADE.LDT"
// greener guild ldt
#define RES_GREENER_GUIDE													"DATA/LDT/newplayer_help.LDT"

#define RES_FNAME_LDT_EVENT_CHECK											"DATA/LDT/EVENT_CHECK.LDT"


//Wedding
#define	RES_FNAME_LDT_WEDDING_MOTION										"DATA/LDT/LOVE_WEDDING_MOTION.LDT"
#define	RES_FNAME_LDT_WEDDING_LEVEL											"DATA/LDT/LOVE_LEVEL.LDT"
#define	RES_FNAME_LDT_WEDDING_BUFF											"DATA/LDT/LOVE_BUFF.LDT"
#define	RES_FNAME_LDT_WEDDING_LP											"DATA/LDT/LOVE_LP.LDT"

















